#*************************************************************************************************************************
#
#Copyright or © or Copr.[DGFIP][2017]
#
#Ce logiciel a été initialement développé par la Direction Générale des 
#Finances Publiques pour permettre le calcul de l'impôt sur le revenu 2013 
#au titre des revenus percus en 2012. La présente version a permis la 
#génération du moteur de calcul des chaînes de taxation des rôles d'impôt 
#sur le revenu de ce millésime.
#
#Ce logiciel est régi par la licence CeCILL 2.1 soumise au droit français 
#et respectant les principes de diffusion des logiciels libres. Vous pouvez 
#utiliser, modifier et/ou redistribuer ce programme sous les conditions de 
#la licence CeCILL 2.1 telle que diffusée par le CEA, le CNRS et l'INRIA  sur 
#le site "http://www.cecill.info".
#
#Le fait que vous puissiez accéder à cet en-tête signifie que vous avez pris 
#connaissance de la licence CeCILL 2.1 et que vous en avez accepté les termes.
#
#**************************************************************************************************************************
regle irisf 1:
application : bareme,batch,iliad;
BIDON=1;

regle irisf 1000140:
application :  iliad;
APPLI_GP      = 0 ;
APPLI_ILIAD   = 1 ;
APPLI_BATCH   = 0 ;
regle irisf 1000150:
application :  batch;
APPLI_GP      = 0 ;
APPLI_ILIAD   = 0 ;
APPLI_BATCH   = 1 ;
regle 1000717:
application : batch, iliad ;
SOMMEA71701 = positif(CELLIERJA) + positif(CELLIERJB) + positif(CELLIERJD) + positif(CELLIERJE)
	     + positif(CELLIERJF) + positif(CELLIERJG) + positif(CELLIERJH) + positif(CELLIERJJ)
	     + positif(CELLIERJK) + positif(CELLIERJL) + positif(CELLIERJM) + positif(CELLIERJN)
	     + positif(CELLIERJO) + positif(CELLIERJP) + positif(CELLIERJQ) + positif(CELLIERJR) 
	     + 0 ;

SOMMEA71702 = positif(CELLIERNA) + positif(CELLIERNB) + positif(CELLIERNC) + positif(CELLIERND)
             + positif(CELLIERNE) + positif(CELLIERNF) + positif(CELLIERNG) + positif(CELLIERNH) 
	     + positif(CELLIERNI) + positif(CELLIERNJ) + positif(CELLIERNK) + positif(CELLIERNL)
	     + positif(CELLIERNM) + positif(CELLIERNN) + positif(CELLIERNO) + positif(CELLIERNP) 
	     + positif(CELLIERNQ) + positif(CELLIERNR) + positif(CELLIERNS) + positif(CELLIERNT) 
	     + 0 ;

regle 1000718:
application : batch, iliad ;

SOMMEA718 = (

   present( BAFV ) + (1 - null( V_FORVA+0 ))
 + present( BAFORESTV ) + present( BAFPVV ) + present( BAF1AV ) 
 + present( BAFC ) + (1 - null( V_FORCA+0 ))
 + present( BAFORESTC ) + present( BAFPVC ) + present( BAF1AC ) 
 + present( BAFP ) + (1 - null( V_FORPA+0 ))
 + present( BAFORESTP ) + present( BAFPVP ) + present( BAF1AP ) 
 + present( BACREV ) + present( 4BACREV ) + present( BA1AV ) + present( BACDEV ) 
 + present( BACREC ) + present( 4BACREC ) + present( BA1AC ) + present( BACDEC ) 
 + present( BACREP ) + present( 4BACREP ) + present( BA1AP ) + present( BACDEP ) 
 + present( BAHREV ) + present( 4BAHREV ) + present( BAHDEV ) 
 + present( BAHREC ) + present( 4BAHREC ) + present( BAHDEC ) 
 + present( BAHREP ) + present( 4BAHREP ) + present( BAHDEP ) 

 + present( MIBVENV ) + present( MIBPRESV ) + present( MIBPVV ) + present( MIB1AV ) + present( MIBDEV ) + present( BICPMVCTV )
 + present( MIBVENC ) + present( MIBPRESC ) + present( MIBPVC ) + present( MIB1AC ) + present( MIBDEC ) + present( BICPMVCTC )
 + present( MIBVENP ) + present( MIBPRESP ) + present( MIBPVP ) + present( MIB1AP ) + present( MIBDEP ) + present( BICPMVCTP )
 + present( BICNOV ) + present( LOCPROCGAV ) + present( BI1AV ) + present( BICDNV ) + present( LOCDEFPROCGAV )
 + present( BICNOC ) + present( LOCPROCGAC ) + present( BI1AC ) + present( BICDNC ) + present( LOCDEFPROCGAC )
 + present( BICNOP ) + present( LOCPROCGAP ) + present( BI1AP ) + present( BICDNP ) + present( LOCDEFPROCGAP )
 + present( BIHNOV ) + present( LOCPROV ) + present( BIHDNV ) + present( LOCDEFPROV )
 + present( BIHNOC ) + present( LOCPROC ) + present( BIHDNC ) + present( LOCDEFPROC )
 + present( BIHNOP ) + present( LOCPROP ) + present( BIHDNP ) + present( LOCDEFPROP )

 + present( MIBMEUV ) + present( MIBGITEV ) + present( LOCGITV ) + present( MIBNPVENV ) + present( MIBNPPRESV ) 
 + present( MIBNPPVV ) + present( MIBNP1AV ) + present( MIBNPDEV ) 
 + present( MIBMEUC ) + present( MIBGITEC ) + present( LOCGITC ) + present( MIBNPVENC ) + present( MIBNPPRESC ) 
 + present( MIBNPPVC ) + present( MIBNP1AC ) + present( MIBNPDEC ) 
 + present( MIBMEUP ) + present( MIBGITEP ) + present( LOCGITP ) + present( MIBNPVENP ) + present( MIBNPPRESP ) 
 + present( MIBNPPVP ) + present( MIBNP1AP ) + present( MIBNPDEP ) 
 + present( MIBNPDCT ) 
 + present( BICREV ) + present( LOCNPCGAV ) + present( LOCGITCV ) + present( BI2AV ) + present( BICDEV ) + present( LOCDEFNPCGAV )
 + present( BICREC ) + present( LOCNPCGAC ) + present( LOCGITCC ) + present( BI2AC ) + present( BICDEC ) + present( LOCDEFNPCGAC )
 + present( BICREP ) + present( LOCNPCGAPAC ) + present( LOCGITCP ) + present( BI2AP ) + present( BICDEP ) + present( LOCDEFNPCGAPAC )
 + present( BICHREV ) + present( LOCNPV ) + present( LOCGITHCV ) + present( BICHDEV ) + present( LOCDEFNPV )
 + present( BICHREC ) + present( LOCNPC ) + present( LOCGITHCC ) + present( BICHDEC ) + present( LOCDEFNPC )
 + present( BICHREP ) + present( LOCNPPAC ) + present( LOCGITHCP ) + present( BICHDEP ) + present( LOCDEFNPPAC )

 + present( BNCPROV ) + present( BNCPROPVV ) + present( BNCPRO1AV ) + present( BNCPRODEV ) + present( BNCPMVCTV )
 + present( BNCPROC ) + present( BNCPROPVC ) + present( BNCPRO1AC ) + present( BNCPRODEC ) + present( BNCPMVCTC )
 + present( BNCPROP ) + present( BNCPROPVP ) + present( BNCPRO1AP ) + present( BNCPRODEP ) + present( BNCPMVCTP )
 + present( BNCREV ) + present( BN1AV ) + present( BNCDEV ) 
 + present( BNCREC ) + present( BN1AC ) + present( BNCDEC ) 
 + present( BNCREP ) + present( BN1AP ) + present( BNCDEP ) 
 + present( BNHREV ) + present( BNHDEV ) 
 + present( BNHREC ) + present( BNHDEC ) 
 + present( BNHREP ) + present( BNHDEP ) 

 + present( BNCNPV ) + present( BNCNPPVV ) + present( BNCNP1AV ) + present( BNCNPDEV ) 
 + present( BNCNPC ) + present( BNCNPPVC ) + present( BNCNP1AC ) + present( BNCNPDEC ) 
 + present( BNCNPP ) + present( BNCNPPVP ) + present( BNCNP1AP ) + present( BNCNPDEP ) 
 + present( BNCNPDCT ) 
 + present ( BNCAABV ) + present( ANOCEP ) + present( PVINVE ) 
 + present( INVENTV ) + present ( BNCAADV ) + present( DNOCEP ) 
 + present ( BNCAABC ) + present( ANOVEP ) + present( PVINCE ) 
 + present( INVENTC ) + present ( BNCAADC ) + present( DNOCEPC )
 + present ( BNCAABP ) + present( ANOPEP ) + present( PVINPE ) 
 + present ( INVENTP ) + present ( BNCAADP ) + present( DNOCEPP )
 + 0
            ) ;

regle 1000719:
application : batch, iliad ;

SOMMEA719 = (

   present( BAEXV ) + present ( BACREV ) + present( 4BACREV ) + present ( BA1AV ) + present ( BACDEV ) 
 + present( BAEXC ) + present ( BACREC ) + present( 4BACREC ) + present ( BA1AC ) + present ( BACDEC ) 
 + present( BAEXP ) + present ( BACREP ) + present( 4BACREP ) + present ( BA1AP ) + present ( BACDEP ) 
 + present( BAHEXV ) + present ( BAHREV ) + present( 4BAHREV ) + present ( BAHDEV ) 
 + present( BAHEXC ) + present ( BAHREC ) + present( 4BAHREC ) + present ( BAHDEC ) 
 + present( BAHEXP ) + present ( BAHREP ) + present( 4BAHREP ) + present ( BAHDEP ) 

 + present( BICEXV ) + present ( BICNOV ) + present ( LOCPROCGAV )
 + present ( BI1AV ) + present ( BICDNV ) + present ( LOCDEFPROCGAV )
 + present( BICEXC ) + present ( BICNOC ) + present ( LOCPROCGAC )
 + present ( BI1AC ) + present ( BICDNC ) + present ( LOCDEFPROCGAC )
 + present( BICEXP ) + present ( BICNOP ) + present ( LOCPROCGAP )
 + present ( BI1AP ) + present ( BICDNP ) + present ( LOCDEFPROCGAP )
 + present( BIHEXV ) + present ( BIHNOV ) + present ( LOCPROV )
 + present ( BIHDNV ) + present ( LOCDEFPROV )
 + present( BIHEXC ) + present ( BIHNOC ) + present ( LOCPROC )
 + present ( BIHDNC ) + present ( LOCDEFPROC )
 + present( BIHEXP ) + present ( BIHNOP ) + present ( LOCPROP )
 + present ( BIHDNP ) + present ( LOCDEFPROP )

 + present( BICNPEXV ) + present ( BICREV ) + present( LOCNPCGAV )
 + present ( BI2AV ) + present ( BICDEV ) + present( LOCDEFNPCGAV )
 + present( BICNPEXC ) + present ( BICREC ) + present( LOCNPCGAC )
 + present ( BI2AC ) + present ( BICDEC ) + present( LOCDEFNPCGAC )
 + present( BICNPEXP ) + present ( BICREP ) + present( LOCNPCGAPAC )
 + present ( BI2AP ) + present ( BICDEP ) + present( LOCDEFNPCGAPAC )
 + present( BICNPHEXV ) + present ( BICHREV ) + present ( LOCNPV )
 + present ( BICHDEV ) + present ( LOCDEFNPV )
 + present( BICNPHEXC ) + present ( BICHREC ) + present ( LOCNPC )
 + present ( BICHDEC ) + present ( LOCDEFNPC )
 + present( BICNPHEXP ) + present ( BICHREP ) + present ( LOCNPPAC )
 + present ( BICHDEP ) + present ( LOCDEFNPPAC )

 + present( BNCEXV ) + present ( BNCREV ) + present ( BN1AV ) + present ( BNCDEV ) 
 + present( BNCEXC ) + present ( BNCREC ) + present ( BN1AC ) + present ( BNCDEC ) 
 + present( BNCEXP ) + present ( BNCREP ) + present ( BN1AP ) + present ( BNCDEP ) 
 + present( BNHEXV ) + present ( BNHREV ) + present ( BNHDEV ) 
 + present( BNHEXC ) + present ( BNHREC ) + present ( BNHDEC ) 
 + present( BNHEXP ) + present ( BNHREP ) + present ( BNHDEP )
 + present( XHONOAAV ) + present( XHONOV ) 
 + present( XHONOAAC ) + present( XHONOC ) 
 + present( XHONOAAP ) + present( XHONOP )

 + present ( BNCNPREXAAV ) + present ( BNCAABV )   + present ( BNCAADV )  + present ( BNCNPREXV ) 
 + present( ANOCEP ) + present( DNOCEP ) + present( PVINVE ) + present( INVENTV )
 + present ( BNCNPREXAAC ) + present ( BNCAABC ) + present ( BNCAADC ) + present ( BNCNPREXC )
 + present( ANOVEP ) + present( DNOCEPC ) + present( PVINCE ) + present( INVENTC )
 + present ( BNCNPREXAAP ) + present ( BNCAABP ) + present ( BNCAADP ) + present ( BNCNPREXP )
 + present( ANOPEP ) + present( DNOCEPP ) + present( PVINPE ) + present( INVENTP )

 + 0
        ) ;

regle 1000530:
application : batch, iliad;

SOMMEA030 =     
                somme(i=1..4: positif(TSHALLOi) + positif(ALLOi)
		+ positif(CARTSPi) + positif(REMPLAPi)
		+ positif(CARTSNBAPi) + positif(REMPLANBPi)
		+ positif(HEURESUPPi)
                + positif(PRBRi)
		+ positif(CARPEPi) + positif(CARPENBAPi)
                + positif(PALIi) + positif(FRNi) + positif(PPETPPi) + positif(PPENHPi)
		+ positif(PENSALPi) + positif(PENSALNBPi)
		)
 + positif(RSAPAC1) + positif(RSAPAC2)
 + positif(FEXP)  + positif(BAFP)  + positif(BAFORESTP) + positif(BAFPVP)  + positif(BAF1AP)
 + positif(BAEXP)  + positif(BACREP) + positif(4BACREP)  
 + positif(BA1AP)  + positif(BACDEP)
 + positif(BAHEXP)  + positif(BAHREP) + positif(4BAHREP) 
 + positif(BAHDEP)
 + positif(MIBEXP) + positif(MIBVENP) + positif(MIBPRESP)  + positif(MIBPVP)  + positif(MIB1AP)  + positif(MIBDEP)
 + positif(BICPMVCTP) + positif(BICEXP) + positif(BICNOP) + positif(BI1AP)  + positif(BICDNP) 
 + positif(BIHEXP) + positif(BIHNOP) + positif(BIHDNP)  
 + positif(MIBNPEXP)  + positif(MIBNPVENP)  + positif(MIBNPPRESP)  + positif(MIBNPPVP)  + positif(MIBNP1AP)  + positif(MIBNPDEP)
 + positif(BICNPEXP)  + positif(BICREP) + positif(BI2AP)  + positif(BICDEP)  
 + positif(BICNPHEXP) + positif(BICHREP) + positif(BICHDEP) 
 + positif(BNCPROEXP)  + positif(BNCPROP)  + positif(BNCPROPVP)  + positif(BNCPRO1AP)  + positif(BNCPRODEP) + positif(BNCPMVCTP)
 + positif(BNCEXP)  + positif(BNCREP) + positif(BN1AP) + positif(BNCDEP)
 + positif(BNHEXP)  + positif(BNHREP)  + positif(BNHDEP) + positif(BNCCRP)
 + positif(BNCNPP)  + positif(BNCNPPVP)  + positif(BNCNP1AP)  + positif(BNCNPDEP)
 + positif(ANOPEP) + positif(PVINPE) + positif(INVENTP) + positif(DNOCEPP) + positif(BNCCRFP)
 + positif(BNCAABP) + positif(BNCAADP)
 + positif(RCSP) + positif(PPEACP) + positif(PPENJP)
 + positif(BAPERPP) + positif(BIPERPP) 
 + positif(PERPP) + positif(PERP_COTP) + positif(RACCOTP) + positif(PLAF_PERPP)
 + somme(i=1..4: positif(PEBFi))
 + positif( COTF1 ) + positif( COTF2 ) + positif( COTF3 ) + positif( COTF4 )
 + positif (BNCNPREXAAP) + positif (BNCNPREXP)
 + positif(AUTOBICVP) + positif(AUTOBICPP) 
 + positif(AUTOBNCP) + positif(LOCPROCGAP) + positif(LOCDEFPROCGAP)
 + positif(LOCPROP) + positif(LOCDEFPROP) + positif(LOCNPCGAPAC) + positif(LOCGITCP) + positif(LOCGITHCP) + positif(LOCDEFNPCGAPAC)
 + positif(LOCNPPAC) + positif(LOCDEFNPPAC) + positif(XHONOAAP) + positif(XHONOP) + positif(XSPENPP)
 + positif(BANOCGAP) + positif(MIBMEUP) + positif(MIBGITEP) + positif(LOCGITP) 
 + 0 ;

regle 1000531:
application : batch, iliad;

SOMMEA031 = (

   positif( TSHALLOC ) + positif( ALLOC ) + positif( HEURESUPC ) + positif( PRBRC ) 
 + positif( PALIC ) + positif( GSALC ) + positif( TSASSUC ) + positif( XETRANC ) 
 + positif( TSELUPPEC ) + positif( EXOCETC ) + positif( FRNC ) 
 + positif( PPETPC ) + positif( PPENHC )  + positif( PCAPTAXC )
 + positif( CARTSC ) + positif( PENSALC ) + positif( REMPLAC ) + positif( CARPEC ) 
 + positif( GLDGRATC ) + positif( SALINTC )
 + positif( GLD1C ) + positif( GLD2C ) + positif( GLD3C ) 

 + positif( BPV18C ) + positif( BPCOPTC ) + positif( BPV40C )
 + positif( BPCOSAC ) + positif( BPVOPTCSC ) + positif( GAINSALAC ) + positif( CVNSALAC )

 + positif( FEXC ) + positif( BAFC ) + positif( BAFORESTC ) + positif( BAFPVC ) + positif( BAF1AC ) 
 + positif( BAEXC ) + positif( BACREC ) + positif( 4BACREC ) + positif( BA1AC ) + positif( BACDEC ) 
 + positif( BAHEXC ) + positif( BAHREC ) + positif( 4BAHREC ) + positif( BAHDEC ) + positif( BAPERPC ) + positif( BANOCGAC ) 
 + positif( AUTOBICVC ) + positif( AUTOBICPC ) + positif( AUTOBNCC ) 
 + positif( MIBEXC ) + positif( MIBVENC ) + positif( MIBPRESC ) + positif( MIBPVC ) 
 + positif( MIB1AC ) + positif( MIBDEC ) + positif( BICPMVCTC )
 + positif( BICEXC ) + positif( BICNOC ) + positif( LOCPROCGAC ) + positif( BI1AC ) + positif( BICDNC ) + positif( LOCDEFPROCGAC )
 + positif( BIHEXC ) + positif( BIHNOC ) + positif( LOCPROC ) + positif( BIHDNC ) + positif( LOCDEFPROC ) + positif( BIPERPC ) 
 + positif( MIBNPEXC ) + positif( MIBNPVENC ) + positif( MIBNPPRESC ) + positif( MIBNPPVC ) + positif( MIBNP1AC ) + positif( MIBNPDEC ) 
 + positif( BICNPEXC ) + positif( BICREC ) + positif( LOCNPCGAC ) + positif( BI2AC ) + positif( BICDEC ) + positif( LOCDEFNPCGAC )
 + positif( MIBMEUC ) + positif( MIBGITEC ) + positif( LOCGITC ) + positif( LOCGITCC ) + positif( LOCGITHCC )
 + positif( BICNPHEXC ) + positif( BICHREC ) + positif( LOCNPC ) + positif( BICHDEC ) + positif( LOCDEFNPC ) 
 + positif( BNCPROEXC ) + positif( BNCPROC ) + positif( BNCPROPVC ) + positif( BNCPRO1AC ) + positif( BNCPRODEC ) + positif( BNCPMVCTC )
 + positif( BNCEXC ) + positif( BNCREC ) + positif( BN1AC ) + positif( BNCDEC ) 
 + positif( BNHEXC ) + positif( BNHREC ) + positif( BNHDEC ) + positif( BNCCRC ) + positif( CESSASSC )
 + positif( XHONOAAC ) + positif( XHONOC ) + positif( XSPENPC )
 + positif( BNCNPC ) + positif( BNCNPPVC ) + positif( BNCNP1AC ) + positif( BNCNPDEC ) 
 + positif( BNCNPREXAAC ) + positif( BNCAABC ) + positif( BNCAADC ) + positif( BNCNPREXC ) + positif( ANOVEP )
 + positif( PVINCE ) + positif( INVENTC ) + positif( DNOCEPC ) + positif( BNCCRFC )
 + positif( RCSC ) + positif( PVSOCC ) + positif( PPEACC ) + positif( PPENJC ) 
 
 + positif( PEBFC ) 

 + positif( PERPC ) + positif( PERP_COTC ) + positif( RACCOTC ) + positif( PLAF_PERPC )
 + positif( PERPPLAFCC ) + positif( PERPPLAFNUC1 ) + positif( PERPPLAFNUC2 ) + positif( PERPPLAFNUC3 )

 + positif( ELURASC )

 + 0 ) ;
regle 1000804:
application : iliad , batch;  


SOMMEA804 = SOMMEANOEXP 
	    + positif ( GLD1V ) + positif ( GLD2V ) + positif ( GLD3V ) 
            + positif ( GLD1C ) + positif ( GLD2C ) + positif ( GLD3C ) 
           ;

SOMMEA805 = SOMMEANOEXP ;

regle 1000993:
application : iliad ;  



INDAUTREQUE9YA = positif (positif( 4BACREC ) + positif( 4BACREP ) + positif( 4BACREV )
 + positif( 4BAHREC ) + positif( 4BAHREP ) + positif( 4BAHREV )
 + positif( ABDETMOINS ) + positif( ABDETPLUS ) + positif( ABIMPMV )
 + positif( ABIMPPV ) + positif( ACODELAISINR ) 
 + positif( ALLO1 ) + positif( ALLO2 ) + positif( ALLO3 )
 + positif( ALLO4 ) + positif( ALLOC ) + positif( ALLOV )
 + positif( ANOCEP ) + positif( ANOPEP )
 + positif( ANOVEP ) + positif( ASCAPA ) + positif( AUTOBICPC )
 + positif( AUTOBICPP ) + positif( AUTOBICPV ) + positif( AUTOBICVC )
 + positif( AUTOBICVP ) + positif( AUTOBICVV ) + positif( AUTOBNCC )
 + positif( AUTOBNCP ) + positif( AUTOBNCV ) + positif( AUTOVERSLIB )
 + positif( AVETRAN ) + positif( BA1AC )
 + positif( BA1AP ) + positif( BA1AV ) + positif( BACDEC )
 + positif( BACDEP ) + positif( BACDEV ) + positif( BACREC )
 + positif( BACREP ) + positif( BACREV ) + positif( BAEXC )
 + positif( BAEXP ) + positif( BAEXV ) + positif( BAF1AC )
 + positif( BAF1AP ) + positif( BAF1AV ) + positif( BAFC )
 + positif( BAFORESTC ) + positif( BAFORESTP ) + positif( BAFORESTV )
 + positif( BAFP ) + positif( BAFPVC ) + positif( BAFPVP )
 + positif( BAFPVV ) + positif( BAFV ) + positif( BAHDEC )
 + positif( BAHDEP ) + positif( BAHDEV ) + positif( BAHEXC )
 + positif( BAHEXP ) + positif( BAHEXV ) + positif( BAHREC )
 + positif( BAHREP ) + positif( BAHREV ) + positif( BAILOC98 )
 + positif( BAPERPC ) + positif( BAPERPP ) + positif( BAPERPV )
 + positif( BASRET ) + positif( BI1AC ) + positif( BI1AP )
 + positif( BI1AV ) + positif( BI2AC ) + positif( BI2AP )
 + positif( BI2AV ) + positif( BICDEC ) + positif( BICDEP )
 + positif( BICDEV ) + positif( BICDNC ) + positif( BICDNP )
 + positif( BICDNV ) + positif( BICEXC ) + positif( BICEXP )
 + positif( BICEXV ) + positif( BICHDEC ) + positif( BICHDEP )
 + positif( BICHDEV ) + positif( BICHREC ) + positif( BICHREP )
 + positif( BICHREV ) + positif( BICNOC ) + positif( BICNOP )
 + positif( BICNOV ) + positif( BICNPEXC ) + positif( BICNPEXP )
 + positif( BICNPEXV ) + positif( BICNPHEXC ) + positif( BICNPHEXP )
 + positif( BICNPHEXV ) + positif( BICREC ) + positif( BICREP )
 + positif( BICREV ) + positif( BIGREST ) + positif( BIHDNC )
 + positif( BIHDNP ) + positif( BIHDNV ) + positif( BIHEXC )
 + positif( BIHEXP ) + positif( BIHEXV ) + positif( BIHNOC )
 + positif( BIHNOP ) + positif( BIHNOV ) + positif( BIPERPC )
 + positif( BIPERPP ) + positif( BIPERPV ) + positif( BN1AC )
 + positif( BN1AP ) + positif( BN1AV ) + positif( BNCAABC )
 + positif( BNCAABP ) + positif( BNCAABV ) + positif( BNCAADC )
 + positif( BNCAADP ) + positif( BNCAADV ) + positif( BNCCRC )
 + positif( BNCCRFC ) + positif( BNCCRFP ) + positif( BNCCRFV )
 + positif( BNCCRP ) + positif( BNCCRV ) + positif( BNCDEC )
 + positif( BNCDEP ) + positif( BNCDEV ) + positif( BNCEXC )
 + positif( BNCEXP ) + positif( BNCEXV ) + positif( BNCNP1AC )
 + positif( BNCNP1AP ) + positif( BNCNP1AV ) + positif( BNCNPC )
 + positif( BNCNPDCT ) + positif( BNCNPDEC ) + positif( BNCNPDEP )
 + positif( BNCNPDEV ) + positif( BNCNPP ) + positif( BNCNPPVC )
 + positif( BNCNPPVP ) + positif( BNCNPPVV ) + positif( BNCNPREXAAC )
 + positif( BNCNPREXAAP ) + positif( BNCNPREXAAV ) + positif( BNCNPREXC )
 + positif( BNCNPREXP ) + positif( BNCNPREXV ) + positif( BNCNPV )
 + positif( BNCPRO1AC ) + positif( BNCPRO1AP ) + positif( BNCPRO1AV )
 + positif( BNCPROC ) + positif( BNCPMVCTV ) + positif( BNCPRODEC )
 + positif( BNCPRODEP ) + positif( BNCPRODEV ) + positif( BNCPROEXC )
 + positif( BNCPROEXP ) + positif( BNCPROEXV ) + positif( BNCPROP )
 + positif( BNCPROPVC ) + positif( BNCPROPVP ) + positif( BNCPROPVV )
 + positif( BNCPROV ) + positif( BNCREC ) + positif( BNCREP )
 + positif( BNCREV ) + positif( BNHDEC ) + positif( BNHDEP )
 + positif( BNHDEV ) + positif( BNHEXC ) + positif( BNHEXP )
 + positif( BNHEXV ) + positif( BNHREC ) + positif( BNHREP )
 + positif( BNHREV ) + positif( BPCOPTV ) + positif( BPCOSAC )
 + positif( BPCOSAV )  
 + positif( BPV18V ) + positif( BPV40V ) 
 + positif( BPVKRI ) + positif( BPVOPTCSV ) + positif( BPVOPTCSV ) + positif( BPVRCM )
 + positif( BRAS ) + positif( CARPEC )
 + positif( CARPENBAC ) + positif( CARPENBAP1 ) + positif( CARPENBAP2 )
 + positif( CARPENBAP3 ) + positif( CARPENBAP4 ) + positif( CARPENBAV )
 + positif( CARPEP1 ) + positif( CARPEP2 ) + positif( CARPEP3 )
 + positif( CARPEP4 ) + positif( CARPEV ) + positif( CARTSC )
 + positif( CARTSNBAC ) + positif( CARTSNBAP1 ) + positif( CARTSNBAP2 )
 + positif( CARTSNBAP3 ) + positif( CARTSNBAP4 ) + positif( CARTSNBAV )
 + positif( CARTSP1 ) + positif( CARTSP2 ) + positif( CARTSP3 )
 + positif( CARTSP4 ) + positif( CARTSV ) + positif( CASEPRETUD )
 + positif( CBETRAN ) + positif( CELLIERHK ) + positif( CELLIERHO )
 + positif( CELLIERHM ) + positif( CELLIERHJ ) + positif( CELLIERHN )
 + positif( CELLIERHL ) + positif( CELREPHS ) + positif( CELREPHR )
 + positif( CELRREDLA ) + positif( CESSASSC ) + positif( CESSASSV )
 + positif( CHENF1 ) + positif( CHENF2 ) + positif( CHENF3 )
 + positif( CHENF4 ) + positif( CHNFAC ) + positif( CHRDED )
 + positif( CHRFAC ) + positif( CIAQCUL ) + positif( CIBOIBAIL )
 + positif( CIDEBITTABAC ) + positif( CIDEP15 )
 + positif( CIIMPPRO ) + positif( CIIMPPRO2 ) + positif( CIINVCORSE )
 + positif( CINE1 ) + positif( CINE2 ) + positif( CINRJBAIL )
 + positif( CMAJ ) + positif( CO2044P ) + positif( CO2047 )
 + positif( CO2102 ) + positif( CO35 ) + positif( CODCHA )
 + positif( CODSIR ) + positif( CONVCREA ) + positif( CONVHAND )
 + positif( COSBC ) + positif( COSBP ) + positif( COSBV )
 + positif( COTF1 ) + positif( COTF2 ) + positif( COTF3 )
 + positif( COTF4 ) + positif( COTFC ) + positif( COTFV )
 + positif( CREAGRIBIO )
 + positif( CREAIDE ) + positif( CREAPP ) + positif( CREARTS )
 + positif( CRECHOBAS ) + positif( CRECHOBOI ) + positif( CRECHOCON2 )
 + positif( CRECONGAGRI ) + positif( CREDPVREP ) + positif( CREFAM )
 + positif( CREFORMCHENT ) + positif( CREINTERESSE ) + positif( CRENRJRNOUV )
 + positif( CREPROSP ) + positif( CRERESTAU ) + positif( CRIGA )
 + positif( DABNCNP1 ) + positif( DABNCNP2 ) + positif( DABNCNP3 )
 + positif( DABNCNP4 ) + positif( DABNCNP5 ) + positif( DABNCNP6 )
 + positif( DAGRI1 ) + positif( DAGRI2 ) + positif( DAGRI3 )
 + positif( DAGRI4 ) + positif( DAGRI5 ) + positif( DAGRI6 )
 + positif( DATDEPETR ) + positif( DATOCEANS ) + positif( DATRETETR )
 + positif( DCSG ) + positif( DEFAA0 ) + positif( DEFAA1 )
 + positif( DEFAA2 ) + positif( DEFAA3 ) + positif( DEFAA4 )
 + positif( DEFAA5 ) + positif( DEFBIC1 ) + positif( DEFBIC2 )
 + positif( DEFBIC3 ) + positif( DEFBIC4 ) + positif( DEFBIC5 )
 + positif( DEFBIC6 ) + positif( DEFRCM ) + positif( DEFRCM2 )
 + positif( DEFRCM3 ) + positif( DEFRCM4 ) + positif( DEPCHOBAS )
 + positif( DEPMOBIL ) + positif( DETS1 ) + positif( DETS2 )
 + positif( DETS3 ) + positif( DETS4 ) + positif( DETSC )
 + positif( DETSV ) + positif( DIREPARGNE ) + positif( DISQUO )
 + positif( DISQUONB ) + positif( DNOCEP )
 + positif( DNOCEPC ) + positif( DNOCEPP ) + positif( DPVRCM )
 + positif( ELURASC ) + positif( ELURASV )
 + positif( ESFP ) + positif( EXOCETC ) + positif( EXOCETV )
 + positif( FCPI ) + positif( FEXC ) + positif( FEXP )
 + positif( FEXV ) + positif( FFIP ) + positif( FIPCORSE )
 + positif( FONCI ) + positif( FONCINB ) + positif( FORET )
 + positif( FRN1 ) + positif( FRN2 ) + positif( FRN3 )
 + positif( FRN4 ) + positif( FRNC ) + positif( FRNV )
 + positif( GAINABDET ) + positif( GLD1C ) + positif( GLD1V )
 + positif( GLD2C ) + positif( GLD2V ) + positif( GLD3C )
 + positif( GLD3V ) + positif( GSALC ) + positif( GSALV )
 + positif( GLDGRATC ) + positif( GLDGRATV )
 + positif( HEURESUPC ) + positif( HEURESUPP1 ) + positif( HEURESUPP2 )
 + positif( HEURESUPP3 ) + positif( HEURESUPP4 ) + positif( HEURESUPV )
 + positif( IMPRET ) + positif( INAIDE ) + positif( INDJNONIMPC )
 + positif( INDJNONIMPV ) + positif( INDLOCNEUF ) + positif( INDLOCRES )
 + positif( IND_TDR ) + positif( INTDIFAGRI ) + positif( INTERE )
 + positif( INTERENB ) 
 + positif( INVDIR2009 ) + positif( INVDOMRET50 )
 + positif( INVDOMRET60 ) + positif( INVENDEB2009 ) + positif( INVENDI )
 + positif( INVIMP ) + positif( INVLGAUTRE )
 + positif( INVLGDEB ) + positif( INVLGDEB2009 ) + positif( INVLGDEB2010 )
 + positif( INVLOCHOTR ) + positif( INVLOCHOTR1 )
 + positif( INVLOCNEUF ) + positif( INVLOCRES ) + positif( INVLOCT1 )
 + positif( INVLOCT2 ) + positif( INVLOG2008 ) + positif( INVLOG2009 )
 + positif( INVLOGSOC ) + positif( INVOMREP ) + positif( INVRETRO1 )
 + positif( INVRETRO2 ) + positif( INVSOC2010 ) + positif( INVSOCNRET )
 + positif( IPBOCH ) + positif( IPCHER ) 
 + positif( IPELUS ) + positif( IPMOND ) + positif( IPPNCS )
 + positif( IPPRICORSE ) + positif( IPRECH ) + positif( IPREP )
 + positif( IPREPCORSE ) + positif( IPSOUR ) + positif( IPSURSI )
 + positif( IPTEFN ) + positif( IPTEFP ) + positif( IPTXMO )
 + positif( IPVLOC ) + positif( LNPRODEF1 ) + positif( LNPRODEF10 )
 + positif( LNPRODEF2 ) + positif( LNPRODEF3 ) + positif( LNPRODEF4 )
 + positif( LNPRODEF5 ) + positif( LNPRODEF6 ) + positif( LNPRODEF7 )
 + positif( LNPRODEF8 ) + positif( LNPRODEF9 ) + positif( LOCDEFNPC )
 + positif( LOCDEFNPCGAC ) + positif( LOCDEFNPCGAPAC ) + positif( LOCDEFNPCGAV )
 + positif( LOCDEFNPPAC ) + positif( LOCDEFNPV ) + positif( LOCDEFPROC )
 + positif( LOCDEFPROCGAC ) + positif( LOCDEFPROCGAP ) + positif( LOCDEFPROCGAV )
 + positif( LOCDEFPROP ) + positif( LOCDEFPROV ) + positif( LOCNPC )
 + positif( LOCNPCGAC ) + positif( LOCNPCGAPAC ) + positif( LOCNPCGAV )
 + positif( LOCNPPAC ) + positif( LOCNPV ) + positif( LOCPROC )
 + positif( LOCPROCGAC ) + positif( LOCPROCGAP ) + positif( LOCPROCGAV )
 + positif( LOCPROP ) + positif( LOCPROV ) + positif( LOCRESINEUV )
 + positif( LOYIMP ) + positif( MEUBLENP ) + positif( MIB1AC )
 + positif( MIB1AP ) + positif( MIB1AV ) 
 + present( BICPMVCTV )+ present( BICPMVCTC )+ present( BICPMVCTP )
 + positif( MIBDEC ) + positif( MIBDEP ) + positif( MIBDEV )
 + positif( MIBEXC ) + positif( MIBEXP ) + positif( MIBEXV )
 + positif( MIBGITEC ) + positif( MIBGITEP ) + positif( MIBGITEV )
 + positif( MIBMEUC ) + positif( MIBMEUP ) + positif( MIBMEUV )
 + positif( MIBNP1AC ) + positif( MIBNP1AP ) + positif( MIBNP1AV )
 + positif( MIBNPDCT ) + positif( MIBNPDEC ) + positif( MIBNPDEP )
 + positif( MIBNPDEV ) + positif( MIBNPEXC ) + positif( MIBNPEXP )
 + positif( MIBNPEXV ) + positif( MIBNPPRESC ) + positif( MIBNPPRESP )
 + positif( MIBNPPRESV ) + positif( MIBNPPVC ) + positif( MIBNPPVP )
 + positif( MIBNPPVV ) + positif( MIBNPVENC ) + positif( MIBNPVENP )
 + positif( MIBNPVENV ) + positif( MIBPRESC ) + positif( MIBPRESP )
 + positif( MIBPRESV ) + positif( MIBPVC ) + positif( MIBPVP )
 + positif( MIBPVV ) + positif( MIBVENC ) + positif( MIBVENP )
 + positif( MIBVENV ) + positif( MOISAN ) + positif( NBACT )
 + positif( NCHENF1 ) + positif( NCHENF2 ) + positif( NCHENF3 )
 + positif( NCHENF4 ) + positif( NRBASE ) + positif( NRETROC40 )
 + positif( NRETROC50 ) + positif( NRINET ) + positif( NUPROP )
 + positif( OPTPLAF15 ) + positif( PAAP ) + positif( PAAV )
 + positif( PALI1 ) + positif( PALI2 ) + positif( PALI3 )
 + positif( PALI4 ) + positif( PALIC ) + positif( PALIV )
 + positif( PATNAT ) + positif( PEA ) + positif( PEBF1 )
 + positif( PEBF2 ) + positif( PEBF3 ) + positif( PEBF4 )
 + positif( PEBFC ) + positif( PEBFV ) + positif( PENSALC )
 + positif( PENSALNBC ) + positif( PENSALNBP1 ) + positif( PENSALNBP2 )
 + positif( PENSALNBP3 ) + positif( PENSALNBP4 ) + positif( PENSALNBV )
 + positif( PENSALP1 ) + positif( PENSALP2 ) + positif( PENSALP3 )
 + positif( PENSALP4 ) + positif( PENSALV ) 
 + positif( PERPC ) + positif( PERPIMPATRIE ) + positif( PERPMUTU )
 + positif( PERPP ) + positif( PERPPLAFCC ) + positif( PERPPLAFCP )
 + positif( PERPPLAFCV ) + positif( PERPPLAFNUC1 ) + positif( PERPPLAFNUC2 )
 + positif( PERPPLAFNUC3 ) + positif( PERPPLAFNUP1 ) + positif( PERPPLAFNUP2 )
 + positif( PERPPLAFNUP3 ) + positif( PERPPLAFNUV1 ) + positif( PERPPLAFNUV2 )
 + positif( PERPPLAFNUV3 ) + positif( PERPV ) + positif( PERP_COTC )
 + positif( PERP_COTP ) + positif( PERP_COTV ) + positif( PETIPRISE )
 + positif( PLAF_PERPC ) + positif( PLAF_PERPP ) + positif( PLAF_PERPV )
 + positif( PPEACC ) + positif( PPEACP ) + positif( PPEACV )
 + positif( PPEISFPIR ) + positif(PPEREVPRO) + positif( PPENHC ) + positif( PPENHP1 )
 + positif( PPENHP2 ) + positif( PPENHP3 ) + positif( PPENHP4 )
 + positif( PPENHV ) + positif( PPENJC ) + positif( PPENJP )
 + positif( PPENJV ) + positif( PPEREVPRO ) + positif( PPETPC )
 + positif( PPETPP1 ) + positif( PPETPP2 ) + positif( PPETPP3 )
 + positif( PPETPP4 ) + positif( PPETPV ) + positif( PPLIB )
 + positif( PRBR1 ) + positif( PRBR2 ) + positif( PRBR3 )
 + positif( PRBR4 ) + positif( PRBRC ) + positif( PRBRV )
 + positif( PREHABT ) + positif( PREHABT1 ) + positif( PREHABT2 ) + positif( PREHABTVT )
 + positif( PREHABTN ) + positif( PREHABTN2 ) + positif( PREMAIDE ) + positif( PREREV )
 + positif( PRESCOMP2000 ) + positif( PRESCOMPJUGE ) + positif( PRETUD )
 + positif( PRETUDANT ) + positif( PRODOM ) + positif( PROGUY )
 + positif( PROVIE ) + positif( PROVIENB ) + positif( PTZDEVDUR )
 + positif( PVINCE ) + positif( PVINPE ) + positif( PVINVE )
 + positif( PVJEUNENT ) + positif( PVREP8 ) + positif( PVSOCC )
 + positif( PVSOCV )
 + positif( R1649 ) + positif( PREREV ) + positif( RACCOTC ) + positif( RACCOTP )
 + positif( RACCOTV ) + positif( RCCURE ) + positif( RCMABD )
 + positif( RCMAV ) + positif( RCMAVFT ) + positif( RCMFR )
 + positif( RCMHAB ) + positif( RCMHAD ) + positif( RCMIMPAT )
 + positif( RCMLIB ) + positif( RCMLIBDIV ) + positif( RCMRDS )
 + positif( RCMSOC ) + positif( RCMTNC ) + positif( RCSC )
 + positif( RCSP ) + positif( RCSV ) + positif( RDCOM )
 + positif( RDDOUP ) + positif( RDENL ) + positif( RDENLQAR )
 + positif( RDENS ) + positif( RDENSQAR ) + positif( RDENU )
 + positif( RDENUQAR ) + positif( RDEQPAHA ) + positif( RDFDOU )
 + positif( RDFOREST ) + positif( RDFORESTGES ) + positif( RDFORESTRA )
 + positif( RDFREP ) + positif( RDGARD1 ) + positif( RDGARD1QAR )
 + positif( RDGARD2 ) + positif( RDGARD2QAR ) + positif( RDGARD3 )
 + positif( RDGARD3QAR ) + positif( RDGARD4 ) + positif( RDGARD4QAR )
 + positif( RDGEQ ) + positif( RDMECENAT ) + positif( RDPRESREPORT )
 + positif( RDREP ) + positif( RDRESU ) + positif( RDSNO )
 + positif( RDSYCJ ) + positif( RDSYPP ) + positif( RDSYVO )
 + positif( RDTECH ) + positif( TAX1649 ) + positif( RE168 )
 + positif( REAMOR ) + positif( REAMORNB ) + positif( REDMEUBLE )
 + positif( REGCI ) + positif( REGPRIV ) + positif( REMPLAC )
 + positif( REMPLANBC ) + positif( REMPLANBP1 ) + positif( REMPLANBP2 )
 + positif( REMPLANBP3 ) + positif( REMPLANBP4 ) + positif( REMPLANBV )
 + positif( REMPLAP1 ) + positif( REMPLAP2 ) + positif( REMPLAP3 )
 + positif( REMPLAP4 ) + positif( REMPLAV ) + positif( RENTAX )
 + positif( RENTAX5 ) + positif( RENTAX6 ) + positif( RENTAX7 )
 + positif( RENTAXNB ) + positif( RENTAXNB5 ) + positif( RENTAXNB6 )
 + positif( RENTAXNB7 ) + positif( REPDON03 ) + positif( REPDON04 )
 + positif( REPDON05 ) + positif( REPDON06 ) + positif( REPDON07 )
 + positif( REPFOR ) + positif( REPGROREP2 )+ positif( REPGROREP1 ) 
 + positif( REPINVDOMPRO2 ) + positif( REPINVDOMPRO3 ) 
 + positif( REPINVLOCINV ) + positif( REPINVLOCREA ) + positif( REPMEUBLE )
 + positif( REPINVTOU ) + positif( INVLOGREHA ) + positif( INVLOGHOT )
 + positif( REPSINFOR ) + positif( REPSNO1 ) + positif( REPSNO2 )
 + positif( REPSNO3 ) + positif( REPSNON) + positif( REPSOF ) + positif( RESIVIEU )
 + positif( RIMOPPAURE ) + positif( RIMOSAUVRF )
 + positif( RIMOPPAUANT ) + positif( RIMOSAUVANT )
 + positif( RESTIMOPPAU ) + positif( RESTIMOSAUV ) + positif( RESTUC )
 + positif( RESTUCNB ) + positif( REVACT ) + positif( REVACTNB )
 + positif( REVFONC ) + positif( REVMAR1 ) + positif( REVMAR2 )
 + positif( REVMAR3 ) + positif( REVPEA ) + positif( REVPEANB )
 + positif( RFDANT ) + positif( RFDHIS )
 + positif( RFDORD ) + positif( RFMIC ) + positif( RFORDI )
 + positif( RFROBOR ) + positif( RINVLOCINV ) + positif( RINVLOCREA )
 + positif( RIRENOV ) + positif( RISKTEC ) + positif( RMOND )
 + positif( RSAFOYER ) + positif( RSAPAC1 )
 + positif( RSAPAC2 ) + positif( RSOCREPRISE ) + positif( RVAIDE )
 + positif( RVB1 ) + positif( RVB2 ) + positif( RVB3 )
 + positif( RVB4 ) + positif( RVCURE )
 + positif( SINISFORET ) 
 + positif( SUBSTITRENTE ) + positif( TSASSUC ) + positif( TSASSUV )
 + positif( TSELUPPEC ) + positif( TSELUPPEV ) + positif( TSHALLO1 )
 + positif( TSHALLO2 ) + positif( TSHALLO3 ) + positif( TSHALLO4 )
 + positif( TSHALLOC ) + positif( TSHALLOV ) + positif( XETRANC )
 + positif( XETRANV ) + positif( XHONOAAC ) + positif( XHONOAAP )
 + positif( XHONOAAV ) + positif( XHONOC ) + positif( XHONOP )
 + positif( XHONOV ) + positif( XSPENPC ) + positif( XSPENPP )
 + positif( XSPENPV ) 
 + positif( RETROCOMLH ) + positif( RETROCOMLI ) + positif( INVOMENTMN )
 + positif( PREHABTN1 ) + positif( CINRJ ) + positif( CRENRJ ) 
 + positif( RFRN2 ) + positif( RFRN3 ) + positif( RFRH1 ) + positif( RFRH2 )
 + positif( ZONEANTEK ) + positif( ISFBASE ) + positif ( ISFPART ) 
 + positif( ISF_LIMINF ) + positif( ISF_LIMSUP ) + positif( ISFCONCUB )
 + positif( ISFFIP ) 
 + positif( ISFDONEURO ) + positif( ISFDONF ) + positif( ISFFCPI )
 + positif( ISFPMEDI ) + positif( ISFPMEIN ) + positif( ISFETRANG ) 
 + positif( CMAJ_ISF ) + positif( MOISAN_ISF ) );
regle 10009931:
application : iliad , batch;  

SOMMEA899 = present( BICEXV ) + present( BICNOV ) + present( BI1AV ) + present( BICDNV )
            + present( BICEXC ) + present( BICNOC ) + present( BI1AC ) + present( BICDNC )
	    + present( BICEXP ) + present( BICNOP ) + present( BI1AP ) + present( BICDNP )
	    + present( BIHEXV ) + present( BIHNOV ) + present( BIHDNV )
	    + present( BIHEXC ) + present( BIHNOC ) + present( BIHDNC )
	    + present( BIHEXP ) + present( BIHNOP ) + present( BIHDNP )
	    ;

SOMMEA859 = present( BICEXV ) + present( BICNOV ) + present( BI1AV ) + present( BICDNV )
            + present( BICEXC ) + present( BICNOC ) + present( BI1AC ) + present( BICDNC )
	    + present( BICEXP ) + present( BICNOP ) + present( BI1AP ) + present( BICDNP )
	    + present( BIHEXV ) + present( BIHNOV ) + present( BIHDNV )
	    + present( BIHEXC ) + present( BIHNOC ) + present( BIHDNC )
	    + present( BIHEXP ) + present( BIHNOP ) + present( BIHDNP )
	    ;

SOMMEA860 = present( BICEXV ) + present( BICNOV ) + present( BI1AV ) + present( BICDNV )
            + present( BICEXC ) + present( BICNOC ) + present( BI1AC ) + present( BICDNC )
	    + present( BICEXP ) + present( BICNOP ) + present( BI1AP ) + present( BICDNP )
	    + present( BIHEXV ) + present( BIHNOV ) + present( BIHDNV )
	    + present( BIHEXC ) + present( BIHNOC ) + present( BIHDNC )
	    + present( BIHEXP ) + present( BIHNOP ) + present( BIHDNP )
            + present( BNCEXV ) + present( BNCREV ) + present( BN1AV ) + present( BNCDEV )
	    + present( BNCEXC ) + present( BNCREC ) + present( BN1AC ) + present( BNCDEC )
	    + present( BNCEXP ) + present( BNCREP ) + present( BN1AP ) + present( BNCDEP )
	    + present( BNHEXV ) + present( BNHREV ) + present( BNHDEV )
	    + present( BNHEXC ) + present( BNHREC ) + present( BNHDEC )
	    + present( BNHEXP ) + present( BNHREP ) + present( BNHDEP )
            ;

SOMMEA895 = present( BAEXV ) + present( BACREV ) + present( 4BACREV )
            + present( BA1AV ) + present( BACDEV )
            + present( BAEXC ) + present( BACREC ) + present( 4BACREC )
            + present( BA1AC ) + present( BACDEC )
	    + present( BAEXP ) + present( BACREP ) + present( 4BACREP )
	    + present( BA1AP ) + present( BACDEP )
	    + present( BAHEXV ) + present( BAHREV ) + present( 4BAHREV )
	    + present( BAHDEV )
	    + present( BAHEXC ) + present( BAHREC ) + present( 4BAHREC )
	    + present( BAHDEC )
	    + present( BAHEXP ) + present( BAHREP ) + present( 4BAHREP )
	    + present( BAHDEP )
	    + present( FEXV ) + present( BAFV ) + (1 - null( V_FORVA+0 )) + present( BAFPVV ) + present( BAF1AV )
            + present( FEXC ) + present( BAFC ) + (1 - null( V_FORCA+0 )) + present( BAFPVC ) + present( BAF1AC )
            + present( FEXP ) + present( BAFP ) + (1 - null( V_FORPA+0 )) + present( BAFPVP ) + present( BAF1AP ) 
	    ;

SOMMEA898 = SOMMEA895 ;

SOMMEA881 =  
	     present( BAEXV ) + present( BACREV ) + present( 4BACREV ) + present( BA1AV ) + present( BACDEV )
           + present( BAEXC ) + present( BACREC ) + present( 4BACREC ) + present( BA1AC ) + present( BACDEC )
	   + present( BAEXP ) + present( BACREP ) + present( 4BACREP ) + present( BA1AP ) + present( BACDEP )
	   + present( BAHEXV ) + present( BAHREV ) + present( 4BAHREV ) + present( BAHDEV )
	   + present( BAHEXC ) + present( BAHREC ) + present( 4BAHREC ) + present( BAHDEC )
	   + present( BAHEXP ) + present( BAHREP ) + present( 4BAHREP ) + present( BAHDEP )

	   + present( BICEXV ) + present( BICNOV ) + present( BI1AV ) + present( BICDNV )
	   + present( BICEXC ) + present( BICNOC ) + present( BI1AC )
	   + present( BICDNC ) + present( BICEXP ) + present( BICNOP ) 
	   + present( BI1AP ) + present( BICDNP ) + present( BIHEXV ) + present( BIHNOV )
	   + present( BIHDNV ) + present( BIHEXC )
	   + present( BIHNOC ) + present( BIHDNC ) 
	   + present( BIHEXP ) + present( BIHNOP ) + present( BIHDNP )
	   + present( BICNPEXV ) + present( BICREV ) + present( BI2AV )
	   + present( BICDEV ) + present( BICNPEXC ) + present( BICREC ) 
	   + present( BI2AC ) + present( BICDEC ) + present( BICNPEXP ) + present( BICREP )
	   + present( BI2AP ) + present( BICDEP ) + present( BICNPHEXV )
	   + present( BICHREV ) + present( BICHDEV ) 
	   + present( BICNPHEXC ) + present( BICHREC ) + present( BICHDEC )
	   + present( BICNPHEXP ) + present( BICHREP ) 
	   + present( BICHDEP ) 
	   + present( LOCPROCGAV ) + present( LOCDEFPROCGAV ) 
	   + present( LOCPROCGAC ) + present( LOCDEFPROCGAC ) 
	   + present( LOCPROCGAP ) + present( LOCDEFPROCGAP )
	   + present( LOCPROV ) + present( LOCDEFPROV ) + present( LOCPROC )
	   + present( LOCDEFPROC ) + present( LOCPROP ) + present( LOCDEFPROP )
	   + present( LOCNPCGAV ) + present( LOCGITCV ) + present( LOCDEFNPCGAV ) 
	   + present( LOCNPCGAC ) + present( LOCGITCC ) + present( LOCDEFNPCGAC ) 
	   + present( LOCNPCGAPAC ) + present( LOCGITCP ) + present( LOCDEFNPCGAPAC )
	   + present( LOCNPV ) + present( LOCGITHCV ) + present( LOCDEFNPV ) 
	   + present( LOCNPC ) + present( LOCGITHCC ) + present( LOCDEFNPC ) 
	   + present( LOCNPPAC ) + present( LOCGITHCP ) + present( LOCDEFNPPAC )

	   + present( BNCEXV ) + present( BNCREV ) + present( BN1AV ) + present( BNCDEV ) 
	   + present( BNCEXC ) + present( BNCREC ) + present( BN1AC ) + present( BNCDEC )
	   + present( BNCEXP ) + present( BNCREP ) + present( BN1AP ) + present( BNCDEP ) 
	   + present( BNHEXV ) + present( BNHREV ) + present( BNHDEV ) 
	   + present( BNHEXC ) + present( BNHREC ) + present( BNHDEC ) 
	   + present( BNHEXP ) + present( BNHREP ) + present( BNHDEP ) 
           + present( XHONOAAV ) + present( XHONOV ) 
	   + present( XHONOAAC ) + present( XHONOC ) 
	   + present( XHONOAAP ) + present( XHONOP )

	   + present ( BNCAABV ) + present ( ANOCEP ) + present ( INVENTV ) 
	   + present ( PVINVE ) + present ( BNCAADV ) + present ( DNOCEP ) 
	   + present ( BNCAABC ) + present ( ANOVEP ) + present ( INVENTC ) 
	   + present ( PVINCE ) + present ( BNCAADC ) + present ( DNOCEPC )
	   + present ( BNCAABP ) + present ( ANOPEP ) + present ( INVENTP )
	   + present ( PVINPE ) + present ( BNCAADP ) + present ( DNOCEPP )
	   ;

SOMMEA861 = SOMMEA881 ;

SOMMEA890 = SOMMEA881  + present( TSHALLOV ) + present( TSHALLOC ) 
		       + present( CARTSV ) + present( CARTSC )
		       + present( CARTSNBAV ) + present( CARTSNBAC ) ;

SOMMEA891 = SOMMEA881 ;

SOMMEA892 = SOMMEA881 ;

SOMMEA893 = SOMMEA881 ;

SOMMEA894 = SOMMEA881 ;

SOMMEA896 = SOMMEA881 ;

SOMMEA897 = SOMMEA881 ;

SOMMEA885 =  present( BA1AV ) + present( BA1AC ) + present( BA1AP )
           + present( BI1AV ) + present( BI1AC ) + present( BI1AP ) 
	   + present( BN1AV ) + present( BN1AC ) + present( BN1AP ) ;

SOMMEA880 =  present ( BICEXV ) + present ( BICNOV ) + present ( BI1AV )
           + present ( BICDNV ) + present ( BICEXC ) + present ( BICNOC )
	   + present ( BI1AC ) + present ( BICDNC ) 
	   + present ( BICEXP ) + present ( BICNOP ) + present ( BI1AP )
	   + present ( BICDNP ) + present ( BIHEXV ) + present ( BIHNOV )
           + present ( BIHDNV ) + present ( BIHEXC )
	   + present ( BIHNOC ) + present ( BIHDNC ) 
	   + present ( BIHEXP ) + present ( BIHNOP ) + present ( BIHDNP )
	   + present ( LOCPROCGAV ) + present ( LOCDEFPROCGAV ) + present ( LOCPROCGAC )
	   + present ( LOCDEFPROCGAC ) + present ( LOCPROCGAP ) + present ( LOCDEFPROCGAP )
	   + present ( LOCPROV ) + present ( LOCDEFPROV ) + present ( LOCPROC )
	   + present ( LOCDEFPROC ) + present ( LOCPROP ) + present ( LOCDEFPROP )
	   ;

SOMMEA874 =  somme(i=V,C,1,2,3,4:present(TSHALLOi) + present(ALLOi) + present(PRBRi) + present(PALIi))
            + present ( CARTSV ) + present ( CARTSC ) + present ( CARTSP1 )
            + present ( CARTSP2 ) + present ( CARTSP3) + present ( CARTSP4 )
            + present ( CARTSNBAV ) + present ( CARTSNBAC ) + present ( CARTSNBAP1 )
            + present ( CARTSNBAP2 ) + present ( CARTSNBAP3) + present ( CARTSNBAP4 )
            + present ( REMPLAV ) + present ( REMPLAC ) + present ( REMPLAP1 )
            + present ( REMPLAP2 ) + present ( REMPLAP3 ) + present ( REMPLAP4 )
            + present ( REMPLANBV ) + present ( REMPLANBC ) + present ( REMPLANBP1 )
            + present ( REMPLANBP2 ) + present ( REMPLANBP3 ) + present ( REMPLANBP4 )
            + present ( CARPEV ) + present ( CARPEC ) + present ( CARPEP1 )
            + present ( CARPEP2 ) + present ( CARPEP3 ) + present ( CARPEP4 )
            + present ( CARPENBAV ) + present ( CARPENBAC ) + present ( CARPENBAP1 )
            + present ( CARPENBAP2 ) + present ( CARPENBAP3 ) + present ( CARPENBAP4 )
            + present ( PENSALV ) + present ( PENSALC ) + present ( PENSALP1 )
            + present ( PENSALP2 ) + present ( PENSALP3 ) + present ( PENSALP4 )
            + present ( PENSALNBV ) + present ( PENSALNBC ) + present ( PENSALNBP1 )
            + present ( PENSALNBP2 ) + present ( PENSALNBP3 ) + present ( PENSALNBP4 )
	    + somme(k=V,C,P: somme (i=C,H: present(BIiNOk)  
		    + somme(j = N: present(BIiDjk))) 
	            + somme (i = I: present(Bi1Ak)) 
		     )
	    + present ( RVB1 ) + present ( RVB2 ) + present ( RVB3 ) + present ( RVB4 )
	    + present ( RENTAX ) + present ( RENTAX5 ) + present ( RENTAX6 ) + present ( RENTAX7 )
	    + present ( RENTAXNB ) + present ( RENTAXNB5 ) + present ( RENTAXNB6 ) + present ( RENTAXNB7 )
	    + present( RCMABD ) + present( RCMHAD ) + present( REGPRIV ) + present( RCMIMPAT )
	    + present( REVACT ) + present( DISQUO ) + present( RESTUC )
	    + present( REVACTNB ) + present( DISQUONB ) +present ( RESTUCNB )
	    + present ( MIBVENV ) + present ( MIBPRESV ) + present ( MIB1AV ) + present ( MIBDEV ) 
	    + present ( MIBVENC ) + present ( MIBPRESC ) + present ( MIB1AC ) + present ( MIBDEC ) 
	    + present ( MIBVENP ) + present ( MIBPRESP ) + present ( MIB1AP ) + present ( MIBDEP ) 
	    + present( LOCPROCGAV ) + present( LOCDEFPROCGAV ) + present( LOCPROCGAC )
	    + present( LOCDEFPROCGAC ) + present( LOCPROCGAP ) + present( LOCDEFPROCGAP )
	    + present( LOCPROV ) + present( LOCDEFPROV ) + present( LOCPROC )
	    + present( LOCDEFPROC ) + present( LOCPROP ) + present( LOCDEFPROP )
	    + present( BICREV ) + present( LOCNPCGAV ) + present( LOCGITCV ) + present( BI2AV ) + present( BICDEV ) + present( LOCDEFNPCGAV ) 
	    + present( BICREC ) + present( LOCNPCGAC ) + present( LOCGITCC ) + present( BI2AC ) + present( BICDEC ) + present( LOCDEFNPCGAC ) 
	    + present( BICREP ) + present( LOCNPCGAPAC ) + present( LOCGITCP ) + present( BI2AP  ) + present( BICDEP ) + present( LOCDEFNPCGAPAC )
	    + present( BICHREV ) + present( LOCNPV ) + present( LOCGITHCV ) + present( BICHDEV ) + present( LOCDEFNPV ) 
	    + present( BICHREC ) + present( LOCNPC ) + present( LOCGITHCC ) + present( BICHDEC ) + present( LOCDEFNPC ) 
	    + present( BICHREP ) + present( LOCNPPAC ) + present( LOCGITHCP ) + present( BICHDEP ) + present( LOCDEFNPPAC )
	    + present( MIBMEUV ) + present( MIBGITEV ) + present( LOCGITV ) + present( MIBNPVENV ) 
	    + present( MIBNPPRESV ) + present( MIBNP1AV ) + present( MIBNPDEV ) 
	    + present( MIBMEUC ) + present( MIBGITEC ) + present( LOCGITC ) + present( MIBNPVENC ) 
	    + present( MIBNPPRESC ) + present( MIBNP1AC ) + present( MIBNPDEC ) 
	    + present( MIBMEUP ) + present( MIBGITEP ) + present( LOCGITP ) + present( MIBNPVENP ) 
	    + present( MIBNPPRESP ) + present( MIBNP1AP ) + present( MIBNPDEP ) 
	    + present ( BNCREV ) + present ( BN1AV ) + present ( BNCDEV )
	    + present ( BNCREC ) + present ( BN1AC ) + present ( BNCDEC )
	    + present ( BNCREP ) + present ( BN1AP ) + present ( BNCDEP )
	    + present ( BNHREV ) + present ( BNHDEV )
	    + present ( BNHREC ) + present ( BNHDEC )
	    + present ( BNHREP ) + present ( BNHDEP )
            + present ( BNCPROV ) + present ( BNCPRO1AV ) + present ( BNCPRODEV ) 
	    + present ( BNCPROC ) + present ( BNCPRO1AC ) + present ( BNCPRODEC ) 
	    + present ( BNCPROP ) + present ( BNCPRO1AP ) + present ( BNCPRODEP ) 
	    + present ( BNCNPV ) + present ( BNCNP1AV ) + present ( BNCNPDEV ) 
	    + present ( BNCNPC ) + present ( BNCNP1AC ) + present ( BNCNPDEC ) 
	    + present ( BNCNPP ) + present ( BNCNP1AP ) + present ( BNCNPDEP ) 
	    + present ( BNCAABV ) + present ( ANOCEP ) + present ( INVENTV ) 
	    + present ( PVINVE ) + present ( BNCAADV ) + present ( DNOCEP ) 
	    + present ( BNCAABC ) + present ( ANOVEP ) + present ( INVENTC ) 
	    + present ( PVINCE ) + present ( BNCAADC ) + present ( DNOCEPC )
	    + present ( BNCAABP ) + present ( ANOPEP ) + present ( INVENTP )
	    + present ( PVINPE ) + present ( BNCAADP ) + present ( DNOCEPP )
	    ;

SOMMEA877 =  present ( BAEXV ) + present ( BACREV ) + present( 4BACREV ) 
	   + present ( BA1AV ) + present ( BACDEV ) + present ( BAEXC ) 
	   + present ( BACREC ) + present( 4BACREC )
	   + present ( BA1AC ) + present ( BACDEC ) + present ( BAEXP ) + present ( BACREP ) 
	   + present( 4BACREP ) + present ( BA1AP ) 
	   + present ( BACDEP ) + present ( BAHEXV ) + present ( BAHREV )  
	   + present( 4BAHREV ) + present ( BAHDEV ) + present ( BAHEXC ) 
	   + present ( BAHREC ) + present( 4BAHREC )
	   + present ( BAHDEC ) + present ( BAHEXP ) + present ( BAHREP )  
	   + present( 4BAHREP ) + present ( BAHDEP ) + present ( BICEXV ) 
	   + present ( BICNOV ) + present ( BI1AV ) + present ( BICDNV ) 
	   + present ( BICEXC ) + present ( BICNOC )  
	   + present ( BI1AC ) + present ( BICDNC ) + present ( BICEXP ) 
           + present ( BICNOP ) + present ( BI1AP ) + present ( BICDNP ) 
           + present ( BIHEXV ) + present ( BIHNOV )  
           + present ( BIHDNV ) + present ( BIHEXC ) + present ( BIHNOC ) 
	   + present ( BIHDNC ) + present ( BIHEXP ) 
	   + present ( BIHNOP ) + present ( BIHDNP ) ;

SOMMEA879 =  
	     present( BACREV ) + present( 4BACREV ) + present( BA1AV ) + present( BACDEV ) 
	   + present( BACREC ) + present( 4BACREC ) + present( BA1AC ) + present( BACDEC ) 
           + present( BACREP ) + present( 4BACREP ) + present( BA1AP ) + present( BACDEP ) 
	   + present( BAHREV ) + present( 4BAHREV ) + present( BAHDEV ) 
	   + present( BAHREC ) + present( 4BAHREC ) + present( BAHDEC ) 
           + present( BAHREP ) + present( 4BAHREP ) + present( BAHDEP ) 
	   
	   + present( BICNOV ) + present( BI1AV ) 
	   + present( BICDNV ) + present( BICNOC )  
	   + present( BI1AC ) + present( BICDNC ) + present( BICNOP ) 
	   + present( BI1AP ) + present( BICDNP )  
	   + present( BIHNOV ) + present( BIHDNV )  
	   + present( BIHNOC ) + present( BIHDNC )  
	   + present( BIHNOP ) + present( BIHDNP )  
	   + present( BICREV ) + present( BI2AV ) + present( BICDEV ) 
	   + present( BICREC ) + present( BI2AC ) 
	   + present( BICDEC ) + present( BICREP )  
	   + present( BI2AP ) + present( BICDEP ) + present( BICHREV ) 
	   + present( BICHDEV ) + present( BICHREC ) 
	   + present( BICHDEC ) + present( BICHREP ) 
	   + present( BICHDEP ) 
	   + present( LOCPROCGAV ) + present( LOCDEFPROCGAV ) + present( LOCPROCGAC )
	   + present( LOCDEFPROCGAC ) + present( LOCPROCGAP ) + present( LOCDEFPROCGAP )
	   + present( LOCPROV ) + present( LOCDEFPROV ) + present( LOCPROC )
	   + present( LOCDEFPROC ) + present( LOCPROP ) + present( LOCDEFPROP )
	   + present( LOCNPCGAV ) + present( LOCGITCV ) + present( LOCDEFNPCGAV ) 
	   + present( LOCNPCGAC ) + present( LOCGITCC ) + present( LOCDEFNPCGAC ) 
	   + present( LOCNPCGAPAC ) + present( LOCGITCP ) + present( LOCDEFNPCGAPAC )
	   + present( LOCNPV ) + present( LOCGITHCV ) + present( LOCDEFNPV ) 
	   + present( LOCNPC ) + present( LOCGITHCC ) + present( LOCDEFNPC ) 
	   + present( LOCNPPAC ) + present( LOCGITHCP ) + present( LOCDEFNPPAC )
	   + present( BNCREV ) + present( BN1AV ) + present( BNCDEV ) 
	   + present( BNCREC ) + present( BN1AC ) + present( BNCDEC ) 
	   + present( BNCREP ) + present( BN1AP ) + present( BNCDEP ) 
	   + present( BNHREV ) + present( BNHDEV ) 
	   + present( BNHREC ) + present( BNHDEC ) 
	   + present( BNHREP ) + present( BNHDEP ) 
	   + present ( BNCAABV ) + present ( ANOCEP ) + present ( INVENTV ) 
	   + present ( PVINVE ) + present ( BNCAADV ) + present ( DNOCEP ) 
	   + present ( BNCAABC ) + present ( ANOVEP ) + present ( INVENTC ) 
	   + present ( PVINCE ) + present ( BNCAADC ) + present ( DNOCEPC )
	   + present ( BNCAABP ) + present ( ANOPEP ) + present ( INVENTP )
	   + present ( PVINPE ) + present ( BNCAADP ) + present ( DNOCEPP )
	   ; 

SOMMEA884 =  present ( TSHALLOV ) + present ( TSHALLOC ) + present ( TSHALLO1 ) + present ( TSHALLO2 ) 
           + present ( TSHALLO3 ) + present ( TSHALLO4 )  
           + present( ALLOV ) + present( ALLOC ) + present( ALLO1 ) + present( ALLO2 ) + present( ALLO3 ) + present( ALLO4 ) 
	   + present ( PALIV ) + present ( PALIC ) + present ( PALI1 ) + present ( PALI2 ) + present ( PALI3 ) + present ( PALI4 ) 
	   + present ( PRBRV ) + present ( PRBRC ) + present ( PRBR1 ) + present ( PRBR2 ) + present ( PRBR3 ) + present ( PRBR4 )  
           + present ( CARTSV ) + present ( CARTSC ) + present ( CARTSP1 )
           + present ( CARTSP2 ) + present ( CARTSP3) + present ( CARTSP4 )
           + present ( CARTSNBAV ) + present ( CARTSNBAC ) + present ( CARTSNBAP1 )
           + present ( CARTSNBAP2 ) + present ( CARTSNBAP3) + present ( CARTSNBAP4 )
           + present ( REMPLAV ) + present ( REMPLAC ) + present ( REMPLAP1 )
           + present ( REMPLAP2 ) + present ( REMPLAP3 ) + present ( REMPLAP4 )
           + present ( REMPLANBV ) + present ( REMPLANBC ) + present ( REMPLANBP1 )
           + present ( REMPLANBP2 ) + present ( REMPLANBP3 ) + present ( REMPLANBP4 )
           + present ( CARPEV ) + present ( CARPEC ) + present ( CARPEP1 )
           + present ( CARPEP2 ) + present ( CARPEP3 ) + present ( CARPEP4 )
           + present ( CARPENBAV ) + present ( CARPENBAC ) + present ( CARPENBAP1 )
           + present ( CARPENBAP2 ) + present ( CARPENBAP3 ) + present ( CARPENBAP4 )
           + present ( PENSALV ) + present ( PENSALC ) + present ( PENSALP1 )
           + present ( PENSALP2 ) + present ( PENSALP3 ) + present ( PENSALP4 )
           + present ( PENSALNBV ) + present ( PENSALNBC ) + present ( PENSALNBP1 )
           + present ( PENSALNBP2 ) + present ( PENSALNBP3 ) + present ( PENSALNBP4 )
	   + present ( REVACT ) + present ( DISQUO ) + present ( REVACTNB ) + present ( DISQUONB ) 
	   + present ( RCMHAD )  
	   + present ( RCMABD )  

	   + present ( RFORDI )  + present ( RFMIC ) 
	   + present ( FONCI ) + present ( REAMOR ) 
	   + present ( BACREV ) + present( 4BACREV )
	   + present ( BACREC ) + present( 4BACREC )
	   + present ( BACREP ) + present( 4BACREP )
	   + present ( BAHREV ) + present( 4BAHREV )
	   + present ( BAHREC ) + present( 4BAHREC )
	   + present ( BAHREP ) + present( 4BAHREP )
	   + present ( BICNOV ) + present ( LOCPROCGAV ) 
	   + present ( BICNOC ) + present ( LOCPROCGAC ) 
	   + present ( BICNOP ) + present ( LOCPROCGAP ) 
	   + present ( BIHNOV ) + present ( LOCPROV )
	   + present ( BIHNOC ) + present ( LOCPROC ) 
	   + present ( BIHNOP ) + present ( LOCPROP )
	   + present ( MIBVENV ) + present ( MIBPRESV ) 
	   + present ( MIBVENC ) + present ( MIBPRESC ) 
	   + present ( MIBVENP ) + present ( MIBPRESP ) 

	   + present ( BICREV ) + present ( LOCNPCGAV ) + present ( LOCGITCV )
	   + present ( BICREC ) + present ( LOCNPCGAC ) + present ( LOCGITCC )
	   + present ( BICREP ) + present ( LOCNPCGAPAC ) + present ( LOCGITCP )
	   + present ( BICHREV ) + present ( LOCNPV ) + present ( LOCGITHCV )
	   + present ( BICHREC ) + present ( LOCNPC ) + present ( LOCGITHCC )
	   + present ( BICHREP ) + present ( LOCNPPAC ) + present ( LOCGITHCP ) 
           + present ( MIBMEUV ) + present ( MIBGITEV ) + present ( LOCGITV ) + present ( MIBNPVENV ) + present ( MIBNPPRESV ) 
	   + present ( MIBMEUC ) + present ( MIBGITEC ) + present ( LOCGITC ) + present ( MIBNPVENC ) + present ( MIBNPPRESC ) 
	   + present ( MIBMEUP ) + present ( MIBGITEP ) + present ( LOCGITP ) + present ( MIBNPVENP ) + present ( MIBNPPRESP ) 
	   + present ( BNCREV ) + present ( BNCREC ) + present ( BNCREP ) 
	   + present ( BNHREV ) + present ( BNHREC ) + present ( BNHREP ) 
	   + present ( BNCPROV ) + present ( BNCPROC ) + present ( BNCPROP ) 

	   + present ( BNCAABV ) + present ( ANOCEP ) + present ( INVENTV ) 
	   + present ( PVINVE ) + present ( BNCAADV ) + present ( DNOCEP ) 
	   + present ( BNCAABC ) + present ( ANOVEP ) + present ( INVENTC ) 
	   + present ( PVINCE ) + present ( BNCAADC ) + present ( DNOCEPC )
	   + present ( BNCAABP ) + present ( ANOPEP ) + present ( INVENTP )
	   + present ( PVINPE ) + present ( BNCAADP ) + present ( DNOCEPP )
	   + present ( BNCNPV ) + present ( BNCNPC ) + present ( BNCNPP ) 

	   ;

SOMMEA538VB =  present( BAFORESTV ) + present( BAFPVV ) + present( BACREV ) + present( 4BACREV ) 
	     + present( BAHREV ) + present( 4BAHREV ) + present( MIBVENV ) + present( MIBPRESV ) 
	     + present( MIBPVV ) + present( BICNOV ) + present( LOCPROCGAV ) + present( BIHNOV ) 
	     + present( LOCPROV ) + present( MIBNPVENV ) + present( MIBNPPRESV ) + present( MIBNPPVV ) 
	     + present( BICREV ) + present( LOCNPCGAV ) + present( LOCGITCV ) + present( BICHREV ) 
	     + present( LOCNPV ) + present( LOCGITHCV )
             + present( BNCPROV ) + present( BNCPROPVV ) + present( BNCREV ) + present( BNHREV ) 
	     + present( BNCNPV ) + present( BNCNPPVV ) + present( ANOCEP ) + present( BNCAABV ) 
	     + present( MIBMEUV ) + present( MIBGITEV ) + present( LOCGITV ) ;

SOMMEA538CB =  present( BAFORESTC ) + present( BAFPVC ) + present( BACREC ) + present( 4BACREC ) 
	     + present( BAHREC ) + present( 4BAHREC ) + present( MIBVENC ) + present( MIBPRESC )
             + present( MIBPVC ) + present( BICNOC ) + present( LOCPROCGAC ) + present( BIHNOC )
             + present( LOCPROC ) + present( MIBNPVENC ) + present( MIBNPPRESC ) + present( MIBNPPVC )
             + present( BICREC ) + present( LOCNPCGAC ) + present( LOCGITCC ) + present( BICHREC ) 
	     + present( LOCNPC ) + present( LOCGITHCC )
             + present( BNCPROC ) + present( BNCPROPVC ) + present( BNCREC ) + present( BNHREC )
	     + present( BNCNPC ) + present( BNCNPPVC ) + present( ANOVEP ) + present( BNCAABC ) 
	     + present( MIBMEUC ) + present( MIBGITEC ) + present( LOCGITC ) ;

SOMMEA538PB =  present( BAFORESTP ) + present( BAFPVP ) + present( BACREP ) + present( 4BACREP ) 
	     + present( BAHREP ) + present( 4BAHREP ) + present( MIBVENP ) + present( MIBPRESP )
             + present( MIBPVP ) + present( BICNOP ) + present( LOCPROCGAP ) + present( BIHNOP )
	     + present( LOCPROP ) + present( MIBNPVENP ) + present( MIBNPPRESP ) + present( MIBNPPVP )
             + present( BICREP ) + present( LOCNPCGAPAC ) + present( LOCGITCP ) + present( BICHREP ) 
	     + present( LOCNPPAC ) + present( LOCGITHCP )
	     + present( BNCPROP ) + present( BNCPROPVP ) + present( BNCREP ) + present( BNHREP )
	     + present( BNCNPP ) + present( BNCNPPVP ) + present( ANOPEP ) + present( BNCAABP ) 
	     + present( MIBMEUP ) + present( MIBGITEP ) + present( LOCGITP ) ;

SOMMEA538VP =  present ( BAF1AV ) + present ( BA1AV ) + present ( MIB1AV ) + present ( BI1AV )
             + present ( MIBNP1AV ) + present ( BI2AV ) + present ( BNCPRO1AV ) + present ( BN1AV )
	     + present ( BNCNP1AV ) + present ( PVINVE ) ;


SOMMEA538CP =  present ( BAF1AC ) + present ( BA1AC ) + present ( MIB1AC ) + present ( BI1AC )
             + present ( MIBNP1AC ) + present ( BI2AC ) + present ( BNCPRO1AC ) + present ( BN1AC )
	     + present ( BNCNP1AC ) + present ( PVINCE ) ;

SOMMEA538PP =  present ( BAF1AP ) + present ( BA1AP ) + present ( MIB1AP ) + present ( BI1AP )
             + present ( MIBNP1AP ) + present ( BI2AP ) + present ( BNCPRO1AP ) + present ( BN1AP )
	     + present ( BNCNP1AP ) + present ( PVINPE ) ;

SOMMEA538 = SOMMEA538VB + SOMMEA538CB + SOMMEA538PB + SOMMEA538VP + SOMMEA538CP + SOMMEA538PP ;

SOMMEA090 =  somme(i=V,C,1..4:TSHALLOi + ALLOi + DETSi + FRNi + PRBRi + PALIi)
            + somme(i=V,C:CARTSi + REMPLAi + PEBFi + CARPEi + PENSALi)
            + somme(i=1..4:CARTSPi + REMPLAPi + PEBFi + CARPEPi + PENSALPi + RVBi)
	    + somme(i=1..3:GLDiV + GLDiC)
	    + RENTAX + RENTAX5 + RENTAX6 + RENTAX7
	    + BPCOSAV + BPCOSAC + GLDGRATV + GLDGRATC
	    ; 

SOMMEA862 =  

      present( MIBEXV ) + present( MIBVENV ) + present( MIBPRESV ) 
    + present( MIBPVV ) + present( MIB1AV ) + present( MIBDEV ) + present( BICPMVCTV )
    + present( MIBEXC ) + present( MIBVENC ) + present( MIBPRESC ) 
    + present( MIBPVC ) + present( MIB1AC ) + present( MIBDEC ) + present( BICPMVCTC ) 
    + present( MIBEXP ) + present( MIBVENP ) + present( MIBPRESP ) 
    + present( MIBPVP ) + present( MIB1AP ) + present( MIBDEP ) + present( BICPMVCTP ) 
    + present( BICEXV ) + present( BICNOV ) + present( LOCPROCGAV ) 
    + present( BI1AV ) + present( BICDNV ) + present( LOCDEFPROCGAV ) 
    + present( BICEXC ) + present( BICNOC ) + present( LOCPROCGAC ) 
    + present( BI1AC ) + present( BICDNC ) + present( LOCDEFPROCGAC ) 
    + present( BICEXP ) + present( BICNOP ) + present( LOCPROCGAP ) 
    + present( BI1AP ) + present( BICDNP ) + present( LOCDEFPROCGAP ) 
    + present( BIHEXV ) + present( BIHNOV ) + present( LOCPROV ) + present( BIHDNV ) + present( LOCDEFPROV ) 
    + present( BIHEXC ) + present( BIHNOC ) + present( LOCPROC ) + present( BIHDNC ) + present( LOCDEFPROC )
    + present( BIHEXP ) + present( BIHNOP ) + present( LOCPROP ) + present( BIHDNP ) + present( LOCDEFPROP ) 

    + present( MIBMEUV ) + present( MIBGITEV ) + present( LOCGITV ) + present( MIBNPEXV ) + present( MIBNPVENV ) 
    + present( MIBNPPRESV ) + present( MIBNPPVV ) + present( MIBNP1AV ) + present( MIBNPDEV ) 
    + present( MIBMEUC ) + present( MIBGITEC ) + present( LOCGITC ) + present( MIBNPEXC ) + present( MIBNPVENC ) 
    + present( MIBNPPRESC ) + present( MIBNPPVC ) + present( MIBNP1AC ) + present( MIBNPDEC ) 
    + present( MIBMEUP ) + present( MIBGITEP ) + present( LOCGITP ) + present( MIBNPEXP ) + present( MIBNPVENP ) 
    + present( MIBNPPRESP ) + present( MIBNPPVP ) + present( MIBNP1AP ) + present( MIBNPDEP ) 
    + present( MIBNPDCT )
    + present( BICNPEXV ) + present( BICREV ) + present( LOCNPCGAV ) + present( LOCGITCV )
    + present( BI2AV ) + present( BICDEV ) + present( LOCDEFNPCGAV )
    + present( BICNPEXC ) + present( BICREC ) + present( LOCNPCGAC ) + present( LOCGITCC )
    + present( BI2AC ) + present( BICDEC ) + present( LOCDEFNPCGAC )
    + present( BICNPEXP ) + present( BICREP ) + present( LOCNPCGAPAC ) + present( LOCGITCP )
    + present( BI2AP ) + present( BICDEP ) + present( LOCDEFNPCGAPAC )
    + present( BICNPHEXV ) + present( BICHREV ) + present( LOCNPV )
    + present( LOCGITHCV ) + present( BICHDEV ) + present( LOCDEFNPV ) 
    + present( BICNPHEXC ) + present( BICHREC ) + present( LOCNPC ) 
    + present( LOCGITHCC ) + present( BICHDEC ) + present( LOCDEFNPC ) 
    + present( BICNPHEXP ) + present( BICHREP ) + present( LOCNPPAC ) 
    + present( LOCGITHCP ) + present( BICHDEP ) + present( LOCDEFNPPAC )

    + present( BNCPROEXV ) + present( BNCPROV ) + present( BNCPROPVV ) 
    + present( BNCPRO1AV ) + present( BNCPRODEV ) + present( BNCPMVCTV )
    + present( BNCPROEXC ) + present( BNCPROC ) + present( BNCPROPVC ) 
    + present( BNCPRO1AC ) + present( BNCPRODEC ) + present( BNCPMVCTC )
    + present( BNCPROEXP ) + present( BNCPROP ) + present( BNCPROPVP ) 
    + present( BNCPRO1AP ) + present( BNCPRODEP ) + present( BNCPMVCTP )
    + present( BNCPMVCTV ) 
    + present( BNCEXV ) + present( BNCREV ) + present( BN1AV ) + present( BNCDEV ) 
    + present( BNCEXC ) + present( BNCREC ) + present( BN1AC ) + present( BNCDEC )
    + present( BNCEXP ) + present( BNCREP ) + present( BN1AP ) + present( BNCDEP ) 
    + present( BNHEXV ) + present( BNHREV ) + present( BNHDEV ) 
    + present( BNHEXC ) + present( BNHREC ) + present( BNHDEC ) 
    + present( BNHEXP ) + present( BNHREP ) + present( BNHDEP ) 

    + present( XSPENPV ) + present( BNCNPV ) + present( BNCNPPVV ) + present( BNCNP1AV ) + present( BNCNPDEV )
    + present( XSPENPC ) + present( BNCNPC ) + present( BNCNPPVC ) + present( BNCNP1AC ) + present( BNCNPDEC ) 
    + present( XSPENPP ) + present( BNCNPP ) + present( BNCNPPVP ) + present( BNCNP1AP ) + present( BNCNPDEP ) 
    + present( BNCNPDCT ) 
    + present( BNCNPREXAAV ) + present( BNCAABV ) + present( BNCAADV ) + present( BNCNPREXV )
    + present( ANOCEP ) + present( DNOCEP ) + present( PVINVE ) + present( INVENTV )
    + present( BNCNPREXAAC ) + present( BNCAABC ) + present( BNCAADC ) + present( BNCNPREXC ) 
    + present( ANOVEP ) + present( DNOCEPC ) + present( PVINCE ) + present( INVENTC )
    + present( BNCNPREXAAP ) + present( BNCAABP ) + present( BNCAADP ) + present( BNCNPREXP ) 
    + present( ANOPEP ) + present( DNOCEPP ) + present( PVINPE ) + present( INVENTP )
	    ;

SOMMEDD55 =

 somme(i=V,C,1,2,3,4: present(TSHALLOi) + present(ALLOi) +  present(PRBRi) + present(PALIi))
 + present ( CARTSV ) + present ( CARTSC ) + present ( CARTSP1 )
 + present ( CARTSP2 ) + present ( CARTSP3) + present ( CARTSP4 )
 + present ( CARTSNBAV ) + present ( CARTSNBAC ) + present ( CARTSNBAP1 )
 + present ( CARTSNBAP2 ) + present ( CARTSNBAP3) + present ( CARTSNBAP4 )
 + present ( REMPLAV ) + present ( REMPLAC ) + present ( REMPLAP1 )
 + present ( REMPLAP2 ) + present ( REMPLAP3 ) + present ( REMPLAP4 )
 + present ( REMPLANBV ) + present ( REMPLANBC ) + present ( REMPLANBP1 )
 + present ( REMPLANBP2 ) + present ( REMPLANBP3 ) + present ( REMPLANBP4 )
 + present ( CARPEV ) + present ( CARPEC ) + present ( CARPEP1 )
 + present ( CARPEP2 ) + present ( CARPEP3 ) + present ( CARPEP4 )
 + present ( CARPENBAV ) + present ( CARPENBAC ) + present ( CARPENBAP1 )
 + present ( CARPENBAP2 ) + present ( CARPENBAP3 ) + present ( CARPENBAP4 )
 + present ( PENSALV ) + present ( PENSALC ) + present ( PENSALP1 )
 + present ( PENSALP2 ) + present ( PENSALP3 ) + present ( PENSALP4 )
 + present ( PENSALNBV ) + present ( PENSALNBC ) + present ( PENSALNBP1 )
 + present ( PENSALNBP2 ) + present ( PENSALNBP3 ) + present ( PENSALNBP4 )
 + present ( PCAPTAXV ) + present ( PCAPTAXC )

 + present ( BACREV ) + present ( 4BACREV ) + present ( BA1AV ) + present ( BACDEV )
 + present ( BACREC ) + present ( 4BACREC ) + present ( BA1AC ) + present ( BACDEC )
 + present ( BACREP ) + present ( 4BACREP ) + present ( BA1AP ) + present ( BACDEP )
 + present ( BAHREV ) + present ( 4BAHREV ) + present ( BAHDEV ) 
 + present ( BAHREC ) + present ( 4BAHREC ) + present ( BAHDEC ) 
 + present ( BAHREP ) + present ( 4BAHREP ) + present ( BAHDEP )

 + present ( BICNOV ) + present ( BI1AV )
 + present ( BICDNV ) + present ( BICNOC )
 + present ( BI1AC ) + present ( BICDNC )
 + present ( BICNOP ) 
 + present ( BI1AP ) + present ( BICDNP ) 
 + present ( BIHNOV ) + present ( BIHDNV )
 + present ( BIHNOC ) 
 + present ( BIHDNC ) + present ( BIHNOP )
 + present ( BIHDNP ) 
 + present ( MIBVENV ) + present ( MIBPRESV ) + present ( MIB1AV )
 + present ( MIBDEV ) + present ( MIBVENC ) + present ( MIBPRESC )
 + present ( MIB1AC ) + present ( MIBDEC ) + present ( MIBVENP )
 + present ( MIBPRESP ) + present ( MIB1AP ) + present ( MIBDEP )
 + present(LOCPROCGAV) + present(LOCDEFPROCGAV) + present( LOCPROCGAC)
 + present(LOCDEFPROCGAC) + present(LOCPROCGAP) + present(LOCDEFPROCGAP)
 + present(LOCPROV) + present(LOCDEFPROV) + present(LOCPROC)
 + present(LOCDEFPROC) + present(LOCPROP) + present(LOCDEFPROP)

 + present(BICREV) + present(LOCNPCGAV) + present ( BI2AV ) + present ( BICDEV ) + present(LOCDEFNPCGAV) 
 + present(BICREC) + present(LOCNPCGAC) + present ( BI2AC ) + present ( BICDEC ) + present(LOCDEFNPCGAC)
 + present(BICREP) + present(LOCNPCGAPAC) + present ( BI2AP ) + present ( BICDEP ) + present(LOCDEFNPCGAPAC)
 + present(BICHREV) + present(LOCNPV) + present(BICHDEV) + present(LOCDEFNPV)
 + present(BICHREC) + present(LOCNPC) + present(BICHDEC) + present(LOCDEFNPC)
 + present(BICHREP) + present(LOCNPPAC) + present(BICHDEP) + present(LOCDEFNPPAC) 
 + present(MIBNPVENV) + present(MIBNPPRESV) + present(MIBNP1AV) + present(MIBNPDEV) 
 + present(MIBNPVENC) + present(MIBNPPRESC) + present(MIBNP1AC) + present(MIBNPDEC) 
 + present(MIBNPVENP) + present(MIBNPPRESP) + present(MIBNP1AP) + present(MIBNPDEP)
 + present(MIBMEUV) + present(MIBGITEV)
 + present(MIBMEUC) + present(MIBGITEC)
 + present(MIBMEUP) + present(MIBGITEP)
 + present(LOCGITCV ) + present(LOCGITCC) + present(LOCGITCP)
 + present(LOCGITHCV) + present(LOCGITHCC) + present(LOCGITHCP)
 + present(LOCGITV) + present(LOCGITC) + present(LOCGITP)

 + present ( BNCREV ) + present ( BN1AV ) + present ( BNCDEV )
 + present ( BNCREC ) + present ( BN1AC ) + present ( BNCDEC )
 + present ( BNCREP ) + present ( BN1AP ) + present ( BNCDEP )
 + present ( BNHREV ) + present ( BNHDEV ) 
 + present ( BNHREC ) + present ( BNHDEC ) 
 + present ( BNHREP ) + present ( BNHDEP )
 + present ( BNCPROV ) + present ( BNCPRO1AV ) + present ( BNCPRODEV )
 + present ( BNCPROC ) + present ( BNCPRO1AC ) + present ( BNCPRODEC )
 + present ( BNCPROP ) + present ( BNCPRO1AP ) + present ( BNCPRODEP )

 + present ( BNCNPV ) + present ( BNCNP1AV ) + present ( BNCNPDEV )
 + present ( BNCNPC ) + present ( BNCNP1AC ) + present ( BNCNPDEC )
 + present ( BNCNPP ) + present ( BNCNP1AP ) + present ( BNCNPDEP )
 + present ( BNCAABV ) + present ( ANOCEP ) + present ( PVINVE ) + present ( BNCAADV ) + present ( DNOCEP )
 + present ( BNCAABC ) + present ( ANOVEP ) + present ( PVINCE ) + present ( BNCAADC ) + present ( DNOCEPC )
 + present ( BNCAABP ) + present ( ANOPEP ) + present ( PVINPE ) + present ( BNCAADP ) + present ( DNOCEPP )
 + present ( INVENTV ) + present ( INVENTC ) + present ( INVENTP )

 ;

SOMMEA802 = present( AUTOBICVV ) + present ( AUTOBICPV ) + present ( AUTOBICVC ) + present ( AUTOBICPC )
	    + present( AUTOBICVP ) + present ( AUTOBICPP ) 
	    + present( AUTOBNCV ) + present ( AUTOBNCC ) + present ( AUTOBNCP ) 
	    + present ( XHONOAAV ) + present ( XHONOV )
	    + present( XHONOAAC ) + present ( XHONOC ) + present ( XHONOAAP ) + present ( XHONOP ) ;

regle 10009932:
application : iliad , batch;  
SOMMEANOEXP = positif ( PEBFV ) + positif ( COTFV ) + positif ( PEBFC ) + positif ( COTFC ) 
              + positif ( PEBF1 ) + positif ( COTF1 ) + positif ( PEBF2 ) + positif ( COTF2 ) 
              + positif ( PEBF3 ) + positif ( COTF3 ) + positif ( PEBF4 ) + positif ( COTF4 ) 
              + positif ( PENSALV ) + positif ( PENSALNBV ) + positif ( PENSALC ) + positif ( PENSALNBC )
              + positif ( PENSALP1 ) + positif ( PENSALNBP1 ) + positif ( PENSALP2 ) + positif ( PENSALNBP2 )
              + positif ( PENSALP3 ) + positif ( PENSALNBP3 ) + positif ( PENSALP4 ) + positif ( PENSALNBP4 )
              + positif ( CARPEV ) + positif ( CARPENBAV ) + positif ( CARPEC ) + positif ( CARPENBAC )
              + positif ( CARPEP1 ) + positif ( CARPENBAP1 ) + positif ( CARPEP2 ) + positif ( CARPENBAP2 )
              + positif ( CARPEP3 ) + positif ( CARPENBAP3 ) + positif ( CARPEP4 ) + positif ( CARPENBAP4 )
              + positif ( CARTSV ) + positif ( CARTSNBAV ) + positif ( CARTSC ) + positif ( CARTSNBAC ) 
              + positif ( CARTSP1 ) + positif ( CARTSNBAP1 ) + positif ( CARTSP2 ) + positif ( CARTSNBAP2 ) 
              + positif ( CARTSP3 ) + positif ( CARTSNBAP3 ) + positif ( CARTSP4 ) + positif ( CARTSNBAP4 ) 
              + positif ( REMPLAV ) + positif ( REMPLANBV ) + positif ( REMPLAC ) + positif ( REMPLANBC )
              + positif ( REMPLAP1 ) + positif ( REMPLANBP1 ) + positif ( REMPLAP2 ) + positif ( REMPLANBP2 )
              + positif ( REMPLAP3 ) + positif ( REMPLANBP3 ) + positif ( REMPLAP4 ) + positif ( REMPLANBP4 )
              + positif ( RENTAX ) + positif ( RENTAX5 ) + positif ( RENTAX6 ) + positif ( RENTAX7 )
              + positif ( RENTAXNB ) + positif ( RENTAXNB5 ) + positif ( RENTAXNB6 ) + positif ( RENTAXNB7 )
              + positif ( FONCI ) + positif ( FONCINB ) + positif ( REAMOR ) + positif ( REAMORNB )
              + positif ( REVACT ) + positif ( REVACTNB ) + positif ( REVPEA ) + positif ( REVPEANB )
              + positif ( PROVIE ) + positif ( PROVIENB ) + positif ( DISQUO ) + positif ( DISQUONB )
              + positif ( RESTUC ) + positif ( RESTUCNB ) + positif ( INTERE ) + positif ( INTERENB )
              + positif( 4BACREV ) + positif( 4BAHREV ) + positif( 4BACREC )
              + positif( 4BAHREC ) + positif( 4BACREP ) + positif( 4BAHREP )
              + 0
             ;

regle 10009933:
application : iliad , batch;  

SOMMEA709 = positif(INVLOCNEUF) + positif(REPINVLOCINV) + positif(RINVLOCINV)
            + positif(INVLOCRES) + positif(RINVLOCREA) + positif(REPINVLOCREA)
            + positif(REPINVTOU) + positif(INVLOGREHA) + positif(INVLOCXN)
            + positif(INVLOCXV)
            + 0
	    ;
regle 10739:
application : iliad , batch ;  

SOMMEA739 = positif(INVSOCNRET) + positif(INVOMSOCKH) + positif(INVOMSOCKI) + positif(INVSOC2010) + positif(INVOMSOCQU) 
	    + positif(INVLOGSOC) + positif(INVOMSOCQJ) + positif(INVOMSOCQS) + positif(INVOMSOCQW) + positif(INVOMSOCQX) 
	    + positif(NRETROC40) + positif(NRETROC50) + positif(RETROCOMMB) + positif(RETROCOMMC) + positif(RETROCOMLH) 
	    + positif(RETROCOMLI) + positif(INVRETRO2) + positif(INVDOMRET60) + positif(INVRETRO1) + positif(INVDOMRET50) 
	    + positif(INVOMRETPO) + positif(INVOMRETPT) + positif(INVOMRETPN) + positif(INVOMRETPP) + positif(INVOMRETPS) 
	    + positif(INVOMRETPU) + positif(INVENDI) + positif(INVOMENTKT) + positif(INVOMENTKU) + positif(INVIMP) 
	    + positif(INVDIR2009) + positif(INVOMRETPR) + positif(INVOMRETPW) + positif(INVLGAUTRE) + positif(INVLGDEB2010) 
	    + positif(INVLOG2009) + positif(INVOMLOGOB) + positif(INVOMLOGOC) + positif(INVOMLOGOM) + positif(INVOMLOGON)
	    + positif(INVOMRETPB) + positif(INVOMRETPF) + positif(INVOMRETPJ) + positif(INVOMRETPA) + positif(INVOMRETPE) 
	    + positif(INVOMRETPI) + positif(INVOMRETPY) + positif(INVOMRETPX) + positif(INVOMENTRG) + positif(INVOMRETPD) 
	    + positif(INVOMRETPH) + positif(INVOMRETPL) + positif(INVOMENTRI) + positif(INVOMLOGOI) + positif(INVOMLOGOJ) 
	    + positif(INVOMLOGOK) + positif(INVOMLOGOP) + positif(INVOMLOGOQ) + positif(INVOMLOGOR) + positif(INVOMENTRL) 
	    + positif(INVOMENTRQ) + positif(INVOMENTRV) + positif(INVOMENTNV) + positif(INVOMENTRK) + positif(INVOMENTRP)
	    + positif(INVOMENTRU) + positif(INVOMENTNU) + positif(INVOMENTRM) + positif(INVOMENTRR) + positif(INVOMENTRW) 
	    + positif(INVOMENTNW) + positif(INVOMENTRO) + positif(INVOMENTRT) + positif(INVOMENTRY) + positif(INVOMENTNY) 
	    + positif(INVOMLOGOT) + positif(INVOMLOGOU) + positif(INVOMLOGOV) + positif(INVOMLOGOW)
	    + 0 ;
regle 10009935:
application : iliad,  batch ;  

SOMMEA700 = 
          (
   present ( BAEXV ) + present ( BACREV ) + present ( 4BACREV ) + present ( BA1AV ) + present ( BACDEV ) 
 + present ( BAEXC ) + present ( BACREC ) + present ( 4BACREC ) + present ( BA1AC ) + present ( BACDEC ) 
 + present ( BAEXP ) + present ( BACREP ) + present ( 4BACREP ) + present ( BA1AP ) + present ( BACDEP ) 
 + present ( BAPERPV ) + present ( BAPERPC ) + present ( BAPERPP )
 + present ( BANOCGAV ) + present ( BANOCGAC ) + present ( BANOCGAP )
 + present ( BAHEXV ) + present ( BAHREV ) + present ( 4BAHREV )
 + present ( BAHEXC ) + present ( BAHREC ) + present ( 4BAHREC )
 + present ( BAHEXP ) + present ( BAHREP ) + present ( 4BAHREP )

 + present (BICEXV ) + present ( BICNOV ) + present ( LOCPROCGAV )
 + present ( BI1AV ) + present ( BICDNV ) + present ( LOCDEFPROCGAV )
 + present (BICEXC ) + present ( BICNOC ) + present ( LOCPROCGAC )
 + present ( BI1AC ) + present ( BICDNC ) + present ( LOCDEFPROCGAC )
 + present (BICEXP ) + present ( BICNOP ) + present ( LOCPROCGAP )
 + present ( BI1AP ) + present ( BICDNP ) + present ( LOCDEFPROCGAP )

 + present (BICNPEXV ) + present ( BICREV ) + present ( LOCNPCGAV ) + present ( LOCGITCV )
 + present ( BI2AV ) + present ( BICDEV ) + present ( LOCDEFNPCGAV )
 + present (BICNPEXC ) + present ( BICREC ) + present ( LOCNPCGAC ) + present ( LOCGITCC )
 + present ( BI2AC ) + present ( BICDEC ) + present ( LOCDEFNPCGAC )
 + present (BICNPEXP ) + present ( BICREP ) + present ( LOCNPCGAPAC ) + present ( LOCGITCP )
 + present ( BI2AP ) + present ( BICDEP ) + present ( LOCDEFNPCGAPAC )

 + present (BNCEXV ) + present ( BNCREV ) + present ( BN1AV ) + present ( BNCDEV )
 + present (BNCEXC ) + present ( BNCREC ) + present ( BN1AC ) + present ( BNCDEC )
 + present (BNCEXP ) + present ( BNCREP ) + present ( BN1AP ) + present ( BNCDEP )
 + present ( BNHEXV ) + present ( BNHREV ) 
 + present ( BNHEXC ) + present ( BNHREC ) 
 + present ( BNHEXP ) + present ( BNHREP ) 
 + present ( XHONOAAV ) + present ( XHONOAAC ) + present ( XHONOAAP )

 + present ( BNCNPREXAAV ) + present ( BNCNPREXV ) + present ( BNCNPREXAAC )
 + present ( BNCNPREXC ) + present ( BNCNPREXAAP ) + present ( BNCNPREXP )
 + present ( BNCAABV ) + present ( BNCAADV ) + present ( ANOCEP ) 
 + present ( PVINVE ) + present ( INVENTV )
 + present ( BNCAABC ) + present ( BNCAADC ) + present ( DNOCEP ) 
 + present ( ANOVEP ) + present ( PVINCE ) + present ( INVENTC )
 + present ( BNCAABP ) + present ( BNCAADP ) + present ( DNOCEPC )
 + present ( ANOPEP ) + present ( PVINPE ) + present ( INVENTP )
 + present ( DNOCEPP )
          ) ;

regle 10009936:
application : iliad , batch;  
V_CNR  =   (V_REGCO+0) dans (2,4);
V_CNR2 =   (V_REGCO+0) dans (2,3,4);
V_CR2  =   (V_REGCO+0) dans (2);
V_EAD  =   (V_REGCO+0) dans (5);
V_EAG  =   (V_REGCO+0) dans (6);

